Azure/azure-iot-sdk-java

device/iot-device-client/pom.xml, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/CustomLogger.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/Message.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsTransport.java, device/iot-device-client/src/main/resources/log4j.properties
=> log4j changes

readme.md
=> Jimaco docfix

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/Twin/TwinCollection.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/Twin/TwinMetadata.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/Twin/TwinProperties.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/Twin/TwinState.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/RegisterManagerParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/util/Tools.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/Helpers.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/FileUploadRequestParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/FileUploadStatusParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/JobsParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/JobsResponseParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/MethodParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/ParserUtilityTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/QueryRequestParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/QueryResponseParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/TwinParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinCollectionTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinMetadataTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinPropertiesTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinStateTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/util/ToolsTest.java
Split Twin from Serializer in deps
=> Split Twin from Serializer in deps

.github/CODING_GUIDELINES.md, .github/PULL_REQUEST_TEMPLATE.md
=> docs: Add commit message guidelines

device/iot-device-samples/send-event-x509/src/main/java/samples/com/microsoft/azure/sdk/iot/SendEventX509.java
=> Wrong Information in Sample for x509 connections

readme.md
- Updated links to API reference
- Removed reference for Android support
- Updated progress on retry policy
=> Update main readme

device/iot-device-client/pom.xml, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/CustomLogger.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/CustomLoggerTest.java
#150 
Device client SDK used old legacy version for Log4j
Upgraded to Log4j version 2
=> Upgraded to Log4J Version 2

iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothubservices/DeviceMethodITonAndroid.java, iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothubservices/DeviceTwinITonAndroid.java, iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothubservices/ReceiveMessagesITonAndroid.java, iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothubservices/SendMessagesITonAndroid.java
=> fix(iot-e2e): remove spaces in test cases' name

edge-e2e/pom.xml, edge-e2e/src/main/java/glue/ModuleGlue.java, edge-e2e/src/main/java/glue/WrapperGlue.java, edge-e2e/src/main/resources/vertx-default-jul-logging.properties
Tim reviewed and signed off on this a while ago but I haven't gotten it checked in because the build is on the floor every time I try.  Submitting for PR signoff so I can try again with the newer scripts.
=> Edge E2E fixes for method calls

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java, iot-e2e-tests/android/app/build.gradle, iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/serviceclient/ExportImportITonAndroid.java, iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/serviceclient/JobClientITonAndroid.java, iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/DeviceMethodCommon.java, iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/DeviceTwinCommon.java, iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/IotHubServicesCommon.java, iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/ReceiveMessagesCommon.java, iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/SendMessagesCommon.java, iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/serviceclient/JobClientCommon.java
=> fix amqp thread leak in reconnection and e2e tests stablility fix for Android

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/auth/IotHubSSLContext.java, iot-e2e-tests/android/app/build.gradle, provisioning/security/x509-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderX509Cert.java
=> fix(device): remove explicit specifiying BC provider to support Android Pie

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
update user agent string for Android
=> fix(device): update user agent string for Android

provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/AttestationMechanism.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/AttestationMechanismType.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroup.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/SymmetricKeyAttestation.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/AttestationMechanismTest.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/SymmetricKeyAttestationTest.java
=> Provisioning Service Symmetric Keys support.

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/Message.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MessageProperty.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceOperations.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessaging.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/MessageTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceOperationsTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnectionTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessagingTest.java
Adding the creation time utc message property to D2C messages
Issue #397
=> feat(iot-dev): Add creation time UTC to Message properties

iot-e2e-tests/android/app/build.gradle, iot-e2e-tests/android/things/build.gradle, iot-e2e-tests/common/pom.xml, iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/ProvisioningCommon.java, iot-e2e-tests/jvm/pom.xml, iot-e2e-tests/pom.xml, pom.xml, provisioning/pom.xml, provisioning/provisioning-device-client/pom.xml, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java, provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/UrlPathBuilderTest.java, provisioning/provisioning-samples/pom.xml, provisioning/provisioning-samples/provisioning-X509-sample/pom.xml, provisioning/provisioning-samples/provisioning-symmetrickey-sample/pom.xml, provisioning/provisioning-samples/provisioning-tpm-sample/pom.xml, provisioning/provisioning-samples/service-bulkoperation-sample/pom.xml, provisioning/provisioning-samples/service-enrollment-group-sample/pom.xml, provisioning/provisioning-samples/service-enrollment-sample/pom.xml, provisioning/provisioning-samples/service-update-enrollment-sample/pom.xml, provisioning/provisioning-service-client/pom.xml, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/CustomAllocationDefinitionTest.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollmentTest.java, provisioning/provisioning-tools/pom.xml, provisioning/provisioning-tools/provisioning-x509-cert-generator/pom.xml, versions.json
Adding device capabilities flag to enrollment groups
=> Release 4/8/2019

deps/pom.xml, provisioning/security/x509-provider/pom.xml
=> fix(iot-deps): upgrade bouncy castle to 1.61 #499

deps/pom.xml, device/iot-device-client/pom.xml, service/iot-service-client/pom.xml, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFeedbackReceivedHandlerTest.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceivedHandlerTest.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendHandlerTest.java
=> fix(deps,device,service): upgrade proton-j to 0.30.0 

iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/serviceclient/RegistryManagerTests.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/IotHubConnectionString.java
Security scope feature won't work properly without this increase in version. Since security scope feature is already checked in, this PR must be merged in before the next release
=> feat(iot-service): Change service api version for security scope feature support

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
Currently, the SDK will only check if messages have expired when the client is fully connected. This PR will periodically check for expired messages even when the client is not connected. This also enables messages to be expired if they are in progress, but no ack is received within the message expiry time
=> feat(iot-dev): Device Client now periodically checks if messages in queue are expired regardless of connection state

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/net/IotHubRejectUri.java
=> Fixed typo (mesage)

provisioning/provisioning-samples/service-bulkoperation-sample/readme.md, provisioning/provisioning-samples/service-enrollment-group-sample/readme.md, provisioning/provisioning-samples/service-enrollment-sample/readme.md, provisioning/provisioning-samples/service-update-enrollment-sample/readme.md
DPS samples linked to 404s, so I have updated them to point to the right url
=> fix(samples): Fixed dead links in provisioning sample readmes

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionDeviceOperation.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionManager.java
Adding a few logs to clarify why a given message failed to be sent within the AMQP layer
=> refactor(iot-dev): Add a few more log statements in AMQP layer

SECURITY.md
=> doc: add security.md to the repo

configure_tls_protocol_version_and_ciphers.md, readme.md
=> doc: added TLS protocol version and ciphers configuration guide

digital-twin/e2e-tests/digital-twin-e2e-tests-common/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/e2e/simulator/TestInterfaceInstance2.java, digital-twin/e2e-tests/digital-twin-e2e-tests-common/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/e2e/tests/DigitalTwinCommandE2ETests.java, digital-twin/service/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/service/DigitalTwinServiceAsyncClientImpl.java, digital-twin/service/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/service/util/Tools.java, digital-twin/service/src/test/java/com/microsoft/azure/sdk/iot/digitaltwin/service/DigitalTwinServiceAsyncClientImplTest.java, digital-twin/service/src/test/java/com/microsoft/azure/sdk/iot/digitaltwin/service/DigitalTwinServiceClientImplTest.java
Fix command response serialization.
Fixes #658
=> Fix command response serialization

digital-twin/device/readme.md, digital-twin/device/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/device/AbstractDigitalTwinComponent.java, digital-twin/device/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/device/DigitalTwinDeviceClient.java, digital-twin/device/src/test/java/com/microsoft/azure/sdk/iot/digitaltwin/device/AbstractDigitalTwinComponentTest.java, digital-twin/device/src/test/java/com/microsoft/azure/sdk/iot/digitaltwin/device/DigitalTwinDeviceClientTest.java, digital-twin/e2e-tests/android/apk/build.gradle, digital-twin/e2e-tests/digital-twin-e2e-tests-common/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/e2e/simulator/TestComponent1.java, digital-twin/e2e-tests/digital-twin-e2e-tests-common/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/e2e/simulator/TestComponent2.java, digital-twin/e2e-tests/digital-twin-e2e-tests-common/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/e2e/tests/DigitalTwinTelemetryE2ETests.java, digital-twin/e2e-tests/digital-twin-e2e-tests-common/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/e2e/tests/DigitalTwinTelemetryParameterizedE2ETests.java, digital-twin/pom.xml, digital-twin/readme.md
=> Digital twin/telemetry explosion

device/iot-device-client/pom.xml
Our Storage SDK version was severely out of date, so let's upgrade it
=> refactor(iot-dev): Upgrade azure storage SDK dependency version

doc/java-devbox-setup.md
=> Update versions for Maven dependencies

vsts/sdl.yaml
this new pool uses a vm in Azure
=> refactor(gate): Change agent pool for SDL

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Device.java
Hello. Fixing a typo, as `Device` does not extend itself
=> doc: fix Device class presentation

iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/X509CertificateGenerator.java
SHA256 + RSA-4096 rather than SHA1 + RSA-1024
=> refactor(e2e): Change test cert generation encryption algorithms

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, device/iot-device-samples/android-sample/app/build.gradle, pom.xml, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
Adding release notes for review : 
- Add proxy support for registry manager (#768) 
- Add proxy support for service client operations (#773)
**Bug Fixes**
- Fix issue where amqp layer didn't recognize an ack to a subscription message that it sent (#778)
- Support Twin Array properties (#770)
**Bug Fixes**
- Fix issue where amqp layer didn't recognize an ack to a subscription message that it sent (#778)
- Fix issue where MQTT didn't url encode application properties correctly (#775)
- Fix bug in amqpws, raise max message size from 1 kb to 16 kb (#767)
- Update proton-j extension to 1.2.3
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.22. …
=> release(2020-05-15): bump package versions

.github/workflows/github_issues.yml
=> Enabling ADO github issue sync for Java repo

iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TransportClientTests.java
subscribeToDeviceMethod(...) is asynchronous (with a callback), but it was being used as if it was synchronous
=> fix(e2e): Fix transportclient tests not waiting for devices to subscribe to methods before invoking methods

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/RegisterManager.java
The json property sent by service has been updated. This code reflects that change for pnp refresh.
=> fix(iot-service): Update json property as sent by pnp service

service/iot-service-samples/pnp-service-sample/pom.xml, service/iot-service-samples/pnp-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/Thermostat.java, service/iot-service-samples/pom.xml
Adding samples for pnp service client - No component
=> feat(samples): Add pnp Thermostat(no component) samples

device/iot-device-samples/pnp-device-sample/TemperatureController/pom.xml, device/iot-device-samples/pnp-device-sample/TemperatureController/src/main/resources/TemperatureController.json, device/iot-device-samples/pnp-device-sample/TemperatureController/src/main/resources/Thermostat.json, device/iot-device-samples/pnp-device-sample/TemperatureController/src/main/resources/log4j.properties, device/iot-device-samples/pnp-device-sample/Thermostat/pom.xml, device/iot-device-samples/pnp-device-sample/Thermostat/src/main/java/samples/com/microsoft/azure/sdk/iot/Thermostat.java, device/iot-device-samples/pnp-device-sample/Thermostat/src/main/resources/Thermostat.json, device/iot-device-samples/pnp-device-sample/Thermostat/src/main/resources/log4j.properties, device/iot-device-samples/pnp-device-sample/pom.xml, device/iot-device-samples/pom.xml
Interface implemented: https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/samples/Thermostat.json
=> feat(sample): Add plug and play Thermostat sample (no-component)

device/iot-device-samples/pnp-device-sample/readme.md, device/iot-device-samples/readme.md
Link to readme: https://github.com/Azure/azure-iot-sdk-java/tree/abmisr/javaReadme/device/iot-device-samples
=> doc(samples): Add readme for pnp device samples

iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/TwinPnPTests.java
This PR is adding e2e tests for PnP model Id changes.
Tested and verified against canary.
Updated with
- modules test cases
- different Authentication mechanisms
=> feat(e2e): Add e2e tests for PnP

readme.md
=> Add survey link in readme.md

.gitignore
A lot has changed in our repo since the last push to this github pages branch, so there are new files to be ignored here
=> Update .gitIgnore to be consistent with Master

device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/pom.xml, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java, device/pnp-helper/src/main/java/com/microsoft/azure/sdk/iot/pnphelpers/PnpHelper.java
Validated with Certification Portal
=> feat(sample): Add support for DPS for Temperature controller sample

iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendHandler.java
=> fix(iot-service): Fix issue where cloud to device messages with no payload would cause NPE when sent

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FeedbackReceiver.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FileUploadNotificationReceiver.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
issue #912 makes it apparent that we need to notify users of this hidden feature of our service client APIs
=> doc(iot-service): Update service client javadocs to include notes about hidden synchronization

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/RegisterManager.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinStateTest.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/TwinPnPTests.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinDevice.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinTest.java
Bring model Id changes from Preview to feature/digitaltwin
=> Bring model Id changes from Preview to feature/digitaltwin

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/RegisterManager.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, device/pom.xml, pom.xml, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
Service API Version changes for device and service client
=> service api version changes for device and service client

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/helpers/Tools.java, service/iot-service-samples/digitaltwin-service-samples/temperature-controller-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/TemperatureController.java, service/iot-service-samples/digitaltwin-service-samples/thermostat-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/Thermostat.java
=> Update API surface for Commands and Update

readme.md
=> chore: Remove survey link from readme

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/BasicDigitalTwin.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinCommandResponse.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinInvokeCommandHeaders.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinInvokeCommandRequestOptions.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinMetadata.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinUpdateRequestOptions.java, service/iot-service-samples/digitaltwin-service-samples/temperature-controller-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/TemperatureController.java, service/iot-service-samples/digitaltwin-service-samples/thermostat-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/Thermostat.java
=> Adding support for BasicDigitalTwin

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnectionTest.java
=> Refactoring code for API version

service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerSample.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleManagerSample.java, service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java
Fix a few minor issues with the samples.
=> Minor fixes to the samples

service/iot-service-samples/digitaltwin-service-samples/temperature-controller-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/TemperatureController.java, service/iot-service-samples/digitaltwin-service-samples/thermostat-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/Thermostat.java
Add Model Id in Digital Twin samples
=> Add Model Id in Digital Twin samples

device/iot-device-client/pom.xml, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java, device/iot-device-samples/pnp-device-sample/thermostat-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/Thermostat.java, service/iot-service-client/pom.xml, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/helpers/UpdateOperationUtility.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinCommandResponse.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinInvokeCommandHeaders.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinInvokeCommandRequestOptions.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinMetadata.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinUpdateRequestOptions.java, service/iot-service-samples/digitaltwin-service-samples/temperature-controller-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/TemperatureController.java, service/iot-service-samples/digitaltwin-service-samples/thermostat-service-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/Thermostat.java, service/iot-service-samples/readme.md
=> Making fixes to java observable returns and addressing minor PR comments

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/helpers/UpdateOperationUtility.java
Add javadocs for update utility
=> Add javadocs for update utility

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinCommandResponse.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinInvokeCommandHeaders.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinInvokeCommandRequestOptions.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinUpdateRequestOptions.java
=> Adding xml comments and use normal getters and setters instead of lombok

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/helpers/Tools.java
=> Throwing correct exceptions

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinCommandResponse.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinMetadata.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/WritableProperty.java
Add writable property for metadata
=> Add writable property for metadata

device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/PnpHelpers.java, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java, device/pom.xml
Moving PnP helpers to device samples
=> Moving Pnp helpers to sample

iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientComponentTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/helpers/DigitalTwinStringSerializer.java
=> Fixing serialization issue in java

device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java
Just like .NET sample [here](https://github.com/Azure/azure-iot-sdk-csharp/pull/1577/files)
=> Add device information reporting to temperature controller sample

service/iot-service-samples/readme.md
Update samples readme to point to master branch
=> Update samples readme to point to master branch

device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/pom.xml, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/PnpConvention.java, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/WritablePropertyResponse.java
Adding helper code for message explosion scenarios
=> refactor(samples): Refactor Pnp helper code for device samples

service/iot-service-samples/digitaltwin-service-samples/pom.xml, service/iot-service-samples/pom.xml, service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java
Service samples already refer to latest release of service client.
=> refactor(samples): Add Digital Twin samples as module to Service Samples

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
Update preview API version to GA
=> Update preview API version to GA

device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java, device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSimpleSample.java, device/iot-device-samples/handle-messages/src/main/java/samples/com/microsoft/azure/sdk/iot/HandleMessages.java, device/iot-device-samples/module-method-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleMethodSample.java, device/iot-device-samples/module-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleTwinSample.java, device/iot-device-samples/send-receive-module-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceiveModuleSample.java, device/iot-device-samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceive.java, device/iot-device-samples/send-receive-x509-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceiveX509.java, service/iot-service-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java
=> refactor(samples): Minor improvements to samples

device/iot-device-samples/device-twin-sample/src/main/resources/log4j.properties, device/iot-device-samples/file-upload-sample/src/main/resources/log4j.properties, device/iot-device-samples/handle-messages/src/main/resources/log4j.properties, device/iot-device-samples/module-invoke-method-sample/src/main/resources/log4j.properties, device/iot-device-samples/module-method-sample/src/main/resources/log4j.properties, device/iot-device-samples/module-twin-sample/src/main/resources/log4j.properties, device/iot-device-samples/send-batch-events/src/main/java/samples/com/microsoft/azure/sdk/iot/SendBatchEvents.java, device/iot-device-samples/send-event-with-proxy/src/main/resources/log4j.properties, device/iot-device-samples/send-event-x509/src/main/java/samples/com/microsoft/azure/sdk/iot/SendEventX509.java, device/iot-device-samples/send-event-x509/src/main/resources/log4j.properties, device/iot-device-samples/send-event/src/main/java/samples/com/microsoft/azure/sdk/iot/SendEvent.java, device/iot-device-samples/send-event/src/main/resources/log4j.properties, device/iot-device-samples/send-receive-module-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceiveModuleSample.java, device/iot-device-samples/send-receive-module-sample/src/main/resources/log4j.properties, device/iot-device-samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceive.java, device/iot-device-samples/send-receive-sample/src/main/resources/log4j.properties, device/iot-device-samples/send-receive-x509-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceiveX509.java, device/iot-device-samples/send-receive-x509-sample/src/main/resources/log4j.properties, device/iot-device-samples/send-serialized-event/src/main/resources/log4j.properties, device/iot-device-samples/transportclient-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/TransportClientSample.java, device/iot-device-samples/transportclient-sample/src/main/resources/log4j.properties
+ TransportClient sample was running into NPE due to null connection string.
+ refactored deprecated usages of setContentType in all samples.
=> refactor(samples): Fix and refactor samples

vsts/generate_javadocs_branch.ps1
=> fix(javadocs): Fix javadocs generation script folder structure

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinDevice.java
Add headers for getter and settter of model Id
=> doc(service): Add headers for getter and settter of model Id

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceTwin.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/ExportImportDevicesParser.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/Tools.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/rules/ThrottleResistantTestRule.java
Also add bulk add functionality to e2e tests to help with upcoming multiplexing tests since we don't have this feature in our registry manager yet, and may never add it
=> refactor(iot-dev, e2e): Fix log statement, add throttle resiliency to tests

.github/workflows/github_issues.yml
=> Bug Fix: GitHub ADO item dupe creation

provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/UrlPathBuilder.java, provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/UrlPathBuilderTest.java
the old flow was url encode -> sign -> url encode again
the correct flow is simply sign -> url encode
fixes issue #989
=> fix(prov-dev): Fix issue where sas token url was url encoded before being signed

.github/workflows/github_issues.yml, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, device/iot-device-samples/android-sample/app/build.gradle, pom.xml, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/UrlPathBuilder.java, provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/UrlPathBuilderTest.java
Since we are doing both a master and a preview release today, might as well make the branches consistent with eachother
=> Merge master into preview

readme.md
=> Update readme with Baltimore cert update info

vsts/generate_javadocs_branch.ps1
=> fix(script): Fix gh-pages generation script

device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/resources/TemperatureController.json, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/resources/Thermostat2.json, device/iot-device-samples/pnp-device-sample/thermostat-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/Thermostat.java
=> Samples(PnP): Change samples to point to new model interfaces

vsts/generate_javadocs_branch.ps1
Adding more granularity to gh-pages generation. 
Tested the script by running the pipeline on my branch - https://github.com/Azure/azure-iot-sdk-java/tree/gh-pages-2020-12-22
=> Adding more granularity to generating gh-pages due to latest release

vsts/generate_javadocs_branch.ps1
=> Fixing formatting issue (extra space)

vsts/generate_javadocs_branch.ps1
=> Merge master to preview

deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/auth/IotHubCertificateManagerTests.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/ExportImportDeviceParserTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpDeviceOperationsTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketHandlerImplTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketImplTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientTest.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/MainApiVerticle.java, provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqttTest.java, provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/parser/DeviceRegistrationResultParserTest.java, provisioning/provisioning-samples/provisioning-X509-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningX509Sample.java, provisioning/provisioning-samples/provisioning-symmetrickey-group-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningSymmetricKeyEnrollmentGroupSample.java, provisioning/provisioning-samples/provisioning-symmetrickey-individual-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningSymmetricKeyIndividualEnrollmentSample.java, provisioning/provisioning-samples/provisioning-tpm-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningTpmSample.java
Fixes ADO Item **[Code maturity] Commented out code (16)**
=> Fixes [Code maturity] Commented out code (16)

deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/auth/IotHubSSLContextTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketHandlerImplTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketImplTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketUpgradeTest.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasToken.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/fileupload/FileUpload.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsSingleMessageTest.java, device/iot-device-samples/send-batch-events/src/main/java/samples/com/microsoft/azure/sdk/iot/SendBatchEvents.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/DesiredPropertiesTests.java, iot-e2e-tests/edge-e2e/src/main/java/glue/ModuleGlue.java, iot-e2e-tests/edge-e2e/src/main/java/glue/RegistryGlue.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/ToolsTest.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/IotHubConnectionStringBuilder.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Message.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollection.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/ToolsTest.java, service/iot-service-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java, service/iot-service-samples/job-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/JobClientSample.java, service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java
Fixes [Java 7] Explicit type can be replaced with <> (153)
=> Fixes [Java 7] Explicit type can be replaced with <> (153)

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpsConnection.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/IotHubServicesCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/HubTierConnectionTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceMethodCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/ReceiveMessagesCommon.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/amqp/ProvisioningAmqpOperations.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqtt.java
Simplify some arithmetic to satisfy the warnings inspector
=> [Numeric Issues]

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/RegisterManagerParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpDeviceOperations.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceMethod.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceMethod.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientTest.java, device/iot-device-samples/device-method-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceMethodSample.java, device/iot-device-samples/module-method-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleMethodSample.java, device/iot-device-samples/transportclient-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/TransportClientSample.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TransportClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/ReceiveMessagesCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/exceptions/ProvisioningServiceClientExceptionManager.java
Removes unnecessary null checks, unwraps single case switch statements, and simplifies some boolean expressions
=> [Control Flow Issues]

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/auth/IotHubSSLContext.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/SignatureHelper.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnection.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FeedbackReceiver.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FileUploadNotificationReceiver.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ConfigurationManangerSample.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerSample.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerX509Sample.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleManagerSample.java, service/iot-service-samples/device-method-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/service/sdk/DeviceMethodSample.java, service/iot-service-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java, service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java
Collapses some multiple catch clauses that all did the same thing, and replace a try/finally with a try with resources
=> [Java 7 warnings]

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinProperty.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/ConfigurationMetricsParserTest.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/TransportClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/net/IotHubUri.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsSingleMessageTest.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/DeviceConnectionString.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/IotHubServicesCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/HubTierConnectionTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TokenRenewalTests.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/amqp/AmqpsProvisioningSaslHandler.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FeedbackBatchMessage.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/ConfigurationMetricsTest.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/ConfigurationTest.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/QueryOptionsTest.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ConfigurationManangerSample.java
replace for loops with foreach loops, remove unnecessary boxing, replace a while loop with a foreach loop
=> [Java 5 warnings]

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpMessage.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketImpl.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/HttpsHsmClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/net/IotHubUri.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSasTokenRenewalHandler.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsTransportManager.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/TopicParser.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceMethodDataTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/hsm/parser/SignRequestTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsRequestTest.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceMethodTest.java, device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MultiplexingClientManager.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TokenRenewalTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/JobClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/DesiredPropertiesTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java, provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/parser/DeviceRegistrationResultParserTest.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/auth/ProvisioningServiceSasTokenTest.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/IotHubConnectionStringTest.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/RegistryManagerTest.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/auth/IotHubServiceSasTokenTest.java
removing unused imports, fixing a few perf warnings, and simplifying a few junit assertions
=> Misc warnings cleanup

deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttConnectionTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttMessageTest.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceTwinTest.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/model/Certificate.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/model/ConnectResponse.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/model/MethodRequestResponse.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/model/RoundtripMethodCallBody.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/UrlPathBuilder.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/auth/ProvisioningConnectionString.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/IotHubConnectionString.java
boolean method is always inverted warning was a false positive, so I suppressed it
=> [Data Flow Issues] Redundant variables

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinProperty.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/TwinMetadata.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketImpl.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceTwin.java, device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java, device/iot-device-samples/module-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleTwinSample.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/EventCallback.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ExportImportTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
- Inspection that can extract common parts from branches of if statement.
- Reports if statements which can be simplified to a single assignment, return or assert statement.
=> [Control flow issues] if statements optimization

deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttConnectionTest.java, deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttMessageTest.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/Property.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/TwinPropertyCallBack.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionString.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasToken.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/TopicParser.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/DesiredPropertiesErrInjTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/DesiredPropertiesTests.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/ProvisioningTask.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RegisterTask.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/AttestationMechanism.java, provisioning/security/tpm-provider-emulator/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMEmulator.java, provisioning/security/tpm-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMHsm.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobResult.java
- [Naming conventions] - Method name same as class name
- [Code style] - Field can be final
=> [CodeStyle] Field can be final

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketUpgrade.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java, device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ClientManagerBase.java
unnecessary null checks preceding instanceof checks ("x instanceof Foo" is always false if x is null), and unnecessary return/continue statements at the end of a block.
=> [Verbose or redundant code constructs]

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ParserUtility.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinTags.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnectionTest.java, device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MultiplexingSample.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientComponentTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/MainApiVerticle.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/parser/ProvisioningErrorParser.java, provisioning/provisioning-samples/provisioning-symmetrickey-individual-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningSymmetricKeyIndividualEnrollmentSample.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpResponseVerification.java, service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/FeedbackReceiverTest.java
This PR contains small warnings fixes that are probably a result of other warning fixes that we've done - eg. we've removed some used code block which made some import statement unnecessary.
=> Misc warnings fix

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/Message.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/TransportClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsReceiverLinkHandler.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/IoTHubConnectionType.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsSingleMessage.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceTwin.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/MessageTest.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/BaseDevice.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Query.java
Most of these are referenced and used, I have added comments where it seemed necessary.
Suppressing these warnings in this PR
=> [Code Maturity] Deprecated member is still used 

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/MethodParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpsConnection.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/util/Tools.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketUpgrade.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/Device.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceTwin.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/PropertyCallBack.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasToken.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/HttpsRequestResponseSerializer.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSenderLinkHandler.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Socks5SocketFactory.java, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java, iot-e2e-tests/edge-e2e/src/main/java/glue/ModuleGlue.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/verticle/DeviceApiVerticle.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/verticle/EventhubApiVerticle.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/verticle/ModuleApiVerticle.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/verticle/RegistryApiVerticle.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/verticle/ServiceApiVerticle.java, iot-e2e-tests/edge-e2e/src/main/java/io/swagger/server/api/verticle/WrapperApiVerticle.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/Query.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/Tools.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/auth/ProvisioningConnectionStringBuilder.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FeedbackBatchMessage.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/IotHubConnectionStringBuilder.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Tools.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/authentication/SasTokenProviderWithSharedAccessKey.java
The individual commit has the details of the warning fixed
=> Code inspection warning fixes

iot-e2e-tests/common/pom.xml, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/TestConstants.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/Tools.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/methods/DeviceMethodTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/JobClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/RegistryManagerTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceMethodCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/GetTwinTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/QueryTwinTests.java
These tests are disabled since the service does not support this type of authentication yet
=> refactor(e2e): Add TokenCredential tests for each service client

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/MethodParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/RegisterManagerParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpDeviceOperations.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpMessage.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/RegisterManager.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceMethod.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/TransportClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenSoftwareAuthenticationProvider.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubX509SoftwareAuthenticationProvider.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/IotHubSasTokenHsmAuthenticationProvider.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsReceiverLinkHandler.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSasTokenRenewalHandler.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSenderLinkHandler.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/TopicParser.java, device/iot-device-samples/device-reconnection-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceClientManagerSample.java, provisioning/security/tpm-provider-emulator/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMEmulator.java, provisioning/security/tpm-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMHsm.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/auth/IotHubServiceSasToken.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerX509Sample.java
[Class structure] Field can be local
[Declaration redundancy] Declaration can have final modifier
=> refactor(codewarnings): Class memeber and local member changes (fix code warnings)

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinParser.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketImpl.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/fileupload/FileUploadTask.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/auth/AuthenticationMethod.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Query.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/UpdateOperationUtility.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/customized/DigitalTwinGetHeaders.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/customized/DigitalTwinUpdateHeaders.java
[Declaration redundancy] Method can be void
=> refactor(codewarnings): Method can be void/unused return value

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnection.java, device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnectionTest.java
See the comment within the code change for more details
=> refactor(iot-dev): Restrict HTTP request support to only localhost requests

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
IoT Hub sends the cloud to device messages as soon as it receives the mqtt subscription on the topic, even before it sends the SUBACK that free's up this client to continue on with its open logic (subscribing to a topic is done in a blocking fashion in this client). By allowing the MQTT layer to receive messages while opening, this deadlock is avoided since we can acknowledge the cloud to device messages and get to the service sending the SUBACK
issue #1154 for additional context
=> fix(iot-dev): Fix deadlock within MQTT layer when client opens with message callback set and cloud to device message queue is full

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpDeviceOperations.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketImpl.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/fileupload/FileUploadTask.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java, device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ClientManagerBase.java, device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java, device/iot-device-samples/pnp-device-sample/thermostat-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/Thermostat.java, device/iot-device-samples/send-serialized-event/src/main/java/samples/com/microsoft/azure/sdk/iot/SendSerializedEvent.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/BaseDevice.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleManagerSample.java
Unused methods, unused variables, and a few other fixes
=> refactor(iot-dev, deps, iot-service): Fix a few miscellaneous warnings

service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
We need to pull the latest (2021-04-12) to enable several new features to take on next.
=> Update hub service client API version

device/iot-device-samples/pnp-device-sample/readme.md
These updates are part of the changes needed to onboard these samples to the Azure Samples browser experience.
=> Update readme for PnP samples

service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerImportExportWithIdentitySample.java
=> refactor(msi-sample): Updating sample with best practices.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, readme.md, supported_platforms.md
fixes #1246
Once we settle on a general format, I'll create a similar doc for our .NET repo
=> Add documentation to repo about which platforms this SDK supports

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinMetadata.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinProperties.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinProperty.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinTags.java, deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/RegisterManager.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java, provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RequestData.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceAuthenticationWithSharedAccessPolicyKey.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollection.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpConnectionHandler.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFeedbackReceivedHandler.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceive.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceivedHandler.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendHandler.java
@timtay-microsoft Here is the PR that would remove all unused protected code.
=> refactor(all): Remove unused code

device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/PnpConvention.java
https://github.com/Azure/azure-iot-sdk-java/issues/1254 fix
Gson cannot serialize  anonymous classes created when use {{}} initialization 
https://stackoverflow.com/questions/39538677/why-does-gson-tojson-always-return-null
=> fix of issue_1254 

vsts/sdl.yaml
The area path recently changed from our re-org, so the SDL pipeline needs to change as well
=> update SDL pipeline to reflect current area path and code owners

readme.md, upcoming_certificate_changes_readme.md
I plan on adding a similar notice on all the other language SDK's readmes as well, minus the Java SDK specific stuff, since this will impact all SDK users
direct link to view the markdown file in its proper form: https://github.com/Azure/azure-iot-sdk-java/blob/timtay/readme/readme.md
=> Add notice and documentation for upcoming Hub + DPS TLS changes

iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningServiceClientTests.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/AllocationPolicy.java, provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroup.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java, provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollmentTest.java
-Fixed issue where the allocation policy was not deserialized correctly because of casing issues (#1286)
-Fixed issue where the device capabilities of an enrollmentGroup were never deserialized
=> fix(prov-serv): Fix issues with deserializing enrollments

major version upgrade migration guide.md
This captures all of the currently approved changes that have been made so far. We can add to it later if we get approval to make further breaking changes
=> Add migration doc to help users upgrade from 1.X.X to 2.X.X releases

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ErrorCodeDescription.java
This matches the work we did on the .NET SDK, but actually removing the unused error codes
=> break(iot-serv): Remove unused service error codes, add descriptions

CODEOWNERS
=> Removing vinagesh from codebase owners list

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/PayloadCollection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/convention/ClientProperties.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/convention/ClientPropertiesCallback.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/convention/ClientPropertyCollection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/convention/PayloadCollection.java, device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/convention/WritablePropertiesRequestsCallback.java
Adding the client property collection class and supporting classes
=> feat(pnp): Add client property classes

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/convention/TelemetryMessage.java
Adding the TelemetryMessage class.
=> feat(pnp): Add telemetry message class

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
=> fix(iot-dev): Fix exception message in mqtt layer

service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java
We plan on deprecating and later removing these async APIs, so make the sample use the sync APIs instead
=> refactor(samples): Remove async calls from service client sample

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, device/iot-device-samples/android-sample/app/build.gradle, pom.xml
- Fixes a small logging regression introduced with bug fix #1357 
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.32.3/jar
=> release(2021-09-15): bump package versions

CODEOWNERS
=> Add Andy to the repos

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsReceiverLinkHandler.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/ReceiveMessagesErrInjTests.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/ReceiveMessagesCommon.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/telemetry/ReceiveMessagesTests.java
Previously, the SDK would encounter a NullPointerException
#1385
=> fix(iot-dev): Fix bug where client failed to handle AMQP partial deliveries correctly

deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ConfigurationContentParser.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Configuration.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ConfigurationContent.java, service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ConfigurationManangerSample.java
See https://github.com/Azure/azure-iot-sdk-csharp/issues/2185. Java was missing this field as well.
=> feat(iot): Add missing moduleContent field to ConfigurationContent class

device/iot-device-samples/device-reconnection-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceClientManagerSample.java, device/iot-device-samples/device-reconnection-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SampleParameters.java, device/iot-device-samples/pom.xml
Task: 12500268
Sample update
We would like to standardize on command line argument for sample input processing.
Implemented command line argument processing using Apache CommonsCli package.
=> Andyk/sample update with CommonsCLI

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java, device/iot-device-samples/android-sample/app/build.gradle, pom.xml, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix AMQP connections not closing connection fully on local connection issues (#1453)
- Fix service client limiting amqps_ws messages to 16 kb (#1450)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.34.1/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/1.33.2/jar
old
{
"device": "1.34.0",
"service": "1.34.0",
"deps": "0.15.2",
"provisioningDevice": "1.11.1",
"provisioningService": "1.9.3"
}
new
{
"device": "1.34.1",
"service": "1.34.0",
"deps": "0.15.2",
"provisioningDevice": "1.11.1",
"provisioningService": "1.9.3"
}
=> release(2022-01-12): bump package versions

vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
Adding SBOM tasks to generate Bill of Materials.
=> sdl(all): Adding SBOM tasks

vsts/sdl.yaml
Old path was deleted and replaced with this new path
=> refactor(ado): Update TSA upload iteration path

iot-e2e-tests/iot-e2e-jvm-tests/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/TokenCredentialTests.java, iot-e2e-tests/iot-e2e-jvm-tests/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/Tools.java, service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/ReactorRunner.java
Also remove some unused imports
=> refactor(e2e): Fix token credential test not using token credential for authentication

SDK v2 migration guide.md, major version upgrade migration guide.md, readme.md
Best viewed in [markdown format here](https://github.com/Azure/azure-iot-sdk-java/blob/timtay/migrationDoc/SDK%20v2%20migration%20guide.md)
=> v2 Migration doc

readme.md, upcoming_certificate_changes_readme.md
Removing references to the v2 preview releases and replacing them with references to the actual v2 releases
=> doc(all): Update readmes now that v2 has been released

device/pom.xml, pom.xml
=> refactor: Remove unnecessary SLF4J dependency

vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
Get the latest ADO changes for component governance in our preview builds as well
=> Merge main into preview

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubStatusCode.java
=> fix(iot-dev): Fix IO errors and time outs not being classified as retryable

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java, pom.xml
See notes in code about this catch
Also upgrading proton-j dependency since it has been a while
=> fix(iot-dev): Handle an issue with proton-j reactor's internal state during cleanup

iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/IntegrationTest.java, iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/Tools.java
=> refactor(e2e): Make SDK less aggressively poll for c2d messages in e2e tests

iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/proxy/extras/SelfSignedSslEngineSource.java
There are 2 issues marked by CodeQL in our Java SDL nightly build - [here](https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=109139&view=results).
.sarif logs show that:
- Unsafe TLS version - [ref](https://rules.sonarsource.com/java/type/Vulnerability/RSPEC-4423) from another similar rule
```json
{
"id" : "SM03640",
"name" : "java/unsafe-tls-version",
"shortDescription" : {
"text" : "Unsafe TLS version"
},
"fullDescription" : {
"text" : "SSL and older TLS versions are known to be vulnerable. TLS 1.3 or at least TLS 1.2 should be used."
},
"defaultConfiguration" : {
"enabled" : true,
"level" : "error"
},
"properties" : {
"tags" : [ "security", "sdl-required", "sdl-recommended", "external/cwe/cwe-327" ],
"description" : "SSL and older TLS versions are known to …
```
=> Update TLS version and fix TrustManager issue for SDL tasks failure

vsts/sdl.yaml
These tests are run in a different pipeline.
=> Fix SDL pipeline not skipping e2e and unit tests

pom.xml
proton-j, proton-j-extensions and paho
=> refactor(iot-dev, iot-serv, prov-dev): Increase transport dependency versions

device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
=> doc(iot-dev): Add missing javadoc comment

pom.xml
- Add notes in javadocs about when subscriptions are preserved [#1619](https://github.com/Azure/azure-iot-sdk-java/pull/1619)
- Added Automatic-Module-Name to jar manifests for Modular Java compatibility [#1635](https://github.com/Azure/azure-iot-sdk-java/pull/1635)
- Upgrade some nested dependencies [#1623](https://github.com/Azure/azure-iot-sdk-java/pull/1623)
- Added Automatic-Module-Name to jar manifests for Modular Java compatibility [#1635](https://github.com/Azure/azure-iot-sdk-java/pull/1635)
- Added Automatic-Module-Name to jar manifests for Modular Java compatibility [#1635](https://github.com/Azure/azure-iot-sdk-java/pull/1635)
- Added Automatic-Module-Name to jar manifests for Modular Java compatibility [#1635](https://github.com/Azure/azure-iot-sdk-java/pull/1635)
- Added …
=> release(2022-12-9): bump package versions

vsts/release/package-maven-artifacts-for-release.ps1
We don't release this package anymore in v2
=> Remove deps package from release pipeline code

service/iot-service-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java
=> Fix DeviceTwinSample

iot-e2e-tests/edge-e2e/src/main/java/glue/ModuleGlue.java, iothub/device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSample.java, iothub/device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSimpleSample.java, vsts/TsaUploadConfigFile.json, vsts/sdl.yaml
Also remove some deprecated analyzers
See also: https://github.com/Azure/azure-iot-sdk-csharp/pull/3206/
=> Update SDL analyzers to latest

iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionString.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenProvidedAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenSoftwareAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenWithRefreshAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubX509HardwareAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubX509SoftwareAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/IotHubSasTokenHsmAuthenticationProvider.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/ClientConfigurationTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionStringTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/ModuleClientTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubAuthenticationProviderTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenAuthenticationProviderTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProviderTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenSoftwareIotHubAuthenticationProviderTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenWithRefreshAuthenticationProviderTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubX509HardwareIotHubAuthenticationProviderTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/hsm/IotHubSasTokenHsmAuthenticationProviderTest.java
Per new designs added in the guidance of E4K adapter
=> Pass MqttGatewayHostName field into connection string

iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
- Send a message after connecting
- Send a message before disconnecting
- Have a will message set to handle ungraceful connection loss events
None of these messages have a defined topic, payload, or QoS yet, so their values are placeholders for now
=> Add lifecycle messages and will message to an MQTT gateway connection

iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientOptions.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/GatewayType.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionString.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/IotHubSasTokenHsmAuthenticationProvider.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt5/E4KConnectionMessagePayload.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt5/E4KConnectionState.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt5/Mqtt5IotHubConnection.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/ClientConfigurationTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionStringTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/E4KConnectionMessagePayloadTest.java
- Send connect/disconnect packet after open/before close
- Add flag for E4K mode
- Create Mqtt5 layer when in E4K mode, otherwise create the existing Mqtt3 layer
=> Port existing E4K changes from previews/E4Kadapter branch

vsts/gradle_build.ps1
The original link of downloading Gradle keeps timing out.
=> Update gradle download link

provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/ProvisioningDeviceClient.java
=> fix(prov-dev): Fix bug where sync overload of register ignores additional data

iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java, iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/ClientConfigurationTest.java, iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/ModuleClientTest.java
client options wasn't being passed to lower layers in a module client createFromEnvironment path.
=> fix(iot-dev): Fix another bug where client options weren't respected

pom.xml
This proton-j release fixes some bugs that may affect long-running AMQP connections.
https://qpid.apache.org/releases/qpid-proton-j-0.34.1/release-notes.html
=> fix(iot-dev): Upgrade proton-j dependency to latest

readme.md
Samples links in the readme go to 404 pages --- updated to reflect latest repo/folder structure.
=> Fix samples links in readme
