- doc/java-devbox-setup.md
Fixed a small typo in the markdown file. Corrected "... take not of ..." to "... take note of ...".
I added a correctly spelled e to not to change something negative to something noticeable. ;-)
> "take not of" typo corrected to "take note of"

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceTwin.java
A `import sun.rmi.server.InactiveGroupException` statement is added to DeviceTwin but the class is not used. This is fortunate as under JDK 9 this fails to compile. This PR removes this import and restores the ability to build this project under JDK 9.
> Remove unused (and unavailable) InactiveGroupException import statement that breaks the build.

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
Create and initialize CustomLogger instance to replace System.out calls.
Github issue (fix#210)
Issue #210 
Log messages were using System.out.
Introduce, initialize and use CustomLogger instead. No tests should be impacted.
> fix(iot-dev): Use CustomLogger in MQTT

- device/iot-device-samples/transportclient-sample/pom.xml
Without the fix, running this sample would fail to an error like:
`Could not find or load main class`
To reproduce without the fix:
```
cd azure-iot-sdk-java/device/iot-device-samples/transportclient-sample
mvn install -DskipTests
java -jar ~/.m2/repository/com/microsoft/azure/sdk/iot/samples/device/transportclient-sample/1.9.0/transportclient-sample-1.9.0-with-deps.jar
Error: Could not find or load main class samples.com.microsoft.azure.sdk.iot.MultiplexingSample
```
The solution is to fix the class name to match what is defined in the source file.
> Fix the class name of a sample

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/SendMessagesCommon.java
`import com.sun.org.apache.bcel.internal.generic.RET;` was added to `SendMessagesCommon`, breaking the build when run under JDK 9, as the `RET` class is not exposed as public API in the module. It also turns out that this class is not used in `SendMessagesCommon`, so removing the import does not appear to result in any issue.
> Removing incorrectly-added import statement

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
https://github.com/Azure/azure-iot-sdk-java/issues/257
The useless log is printed every 10ms as long as loglevel is set to DEBUG.
Since the received message has already been logged in onMessageReceived, the log in handleMessage is redundant and can be removed.
Another INFO log is added into addReceivedMessagesOverHttpToReceivedQueue
so all received messages are equally logged in transport level.
Note, the change in IotHubTransportTest.java is not for covering added code. But if without this change, the added logging in addReceivedMessagesOverHttpToReceivedQueue() will result in jmockit to complain missing invocation of HttpsIotHubConnection.receiveMessage(). Not sure …
> Fix issue 257: remove unnecessary logging in IotHubTransport

- deps/pom.xml
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/TwinCollection.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/Helpers.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinCollectionTest.java
#290 DeviceTwin.getTwin for module twin with IllegalArgumentException
Module twin introduced extra level in json format. Before it was just 5, now 6 are used
Check for maximum levels in json format increased from 5 to 6. Additionally wrong usage of TwinCollection.Entry was changed to Map.Entry<String, Object> so that it can be compiled with stricter rules like Eclipse is using (didn't compile with Eclipse so far). Version of iot-deps was increased from 0.6.1 to 0.6.2-SNAPSHOT for testing purpose (please adapt accordingly).
> Fixed extra level for module twins

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/QueryResponseParser.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollection.java
Fix for issue #296 
Device twins with valid UTF-8 characters, that used more than 1 byte like '§', caused an IllegalArgumentException, since the check in ParserUtility was wrong
Removed the call to the wrong validation in ParserUtilitiy and added check against empty string. Only problem left is that property and tag keys could now contain invalid characters. But this should not never happen, since this is already checked by the IoT Hub service.
> Device twins can now contain double byte UTF-8 characters - fix for bug#296

- service/iot-service-samples/device-manager-sample/pom.xml
Fix  for #299 
device-manager-sample project uses classes from java.time package that are only available since Java 1.8. But project is set up to compile with Java 1.6
Changed compiler settings of project device-manager-sample to 1.8
> Set Java version from 1.6 to 1.8 to make device-manager-sample compilable again

- iot-e2e-tests/jvm/pom.xml
- iot-e2e-tests/jvm/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/serviceclient/ExportImportIT.java
e2e test for importing and exporting devices didn't compile and was ignored due to service problems
Set Java compiler to version 1.8 and removed Ignore attribute from unit test
> Reactivated e2e tests for import/export of devices

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ExportImportDeviceParser.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/ExportImportDeviceParserTest.java
- iot-e2e-tests/jvm/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/serviceclient/ExportImportIT.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ExportImportDevice.java
Partial fix for #298
Importing and exporting devices didn't support tags
Added the tags section to the import and export json serialization/deserialization
> Importing and exporting devices supports tags now

- device/iot-device-client/pom.xml
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/CustomLogger.java
Solved #310 and older closed one as well
Device client SDK used log4j directly, forcing users to use this kind of logging implementation. Therefore usage of other logging implementations like logback were not possible
CustomLogger class of Device client SDK uses logging facade slf4j now
> Changed from direct usage of log4j to logging facacde from slf4j

- iot-e2e-tests/jvm/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothubservices/ReceiveMessagesIT.java
- iot-e2e-tests/jvm/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/serviceclient/RegistryManagerIT.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/RegistryManagerTest.java
A few test classes reference a Module class, but this results in compilation issues under JDK 9+, because java.lang.Module is implicitly imported, but in the test classes I fix in this PR, the Module class that is intended to be used is another, IoT-specific class.
> Fix build failures under JDK 9

- deps/pom.xml
- device/iot-device-client/pom.xml
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessaging.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessagingTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/ErrorInjectionHelper.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/SendMessagesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/iothubservices/TransportClientCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/serviceclient/ExportImportCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/serviceclient/JobClientCommon.java
- iot-e2e-tests/jvm/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/serviceclient/ExportImportIT.java
- provisioning/provisioning-device-client/pom.xml
- provisioning/provisioning-service-client/pom.xml
- service/iot-service-client/pom.xml
TransportClientIT will always fail on any retry attempts because it maintains the connection strings of deleted devices and tries to use them on the 2nd/3rd attempt. Because of that, the test will always fail with "Device not found" because the connection string belongs to a deleted device
JobClientIT and ExportImportIT suffer from when their spawned jobs take a while to run. Currently, our tests are expecting the jobs to finish too quickly, so this PR will up those time limits. Also, ExportImportIT needed to handle cases when the service throttles its job creation.
Unit tests are failing due to a known jmockit bug where running tests in parallel can cause what are essentially random failures. Context is [here](https://github.com/jmockit/jmockit1/issues/263). Since we run tests in …
> Stabilizing unit tests and some E2E tests

- iot-e2e-tests/jvm/pom.xml
- iot-e2e-tests/jvm/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/serviceclient/ExportImportIT.java
Disabling the JobClientIT test suite on the JVM since it is still intermittently failing due to possible service side issue
> refactor(e2e test): Disable job IT on JVM

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientTest.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothubservices/FileUploadAndroidRunner.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/FileUploadTests.java
- iot-e2e-tests/jvm/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothubservices/FileUploadJVMRunner.java
Adding e2e test, too
fixes #371 
Currently, file upload code path throws unsupported operation exception when using self signed or ca signed certs as the authentication mechanism of your device client. While the service does not allow CA signed certs for file upload, it does allow self signed certs.
Removed the unsupported operation exception, and added a note about the gap with CA signed certs. Also added end to end tests to cover this scenario
> feat(iot-dev): Enable fileupload with SelfSigned device client

- jenkins/linux_java.sh
The hardcoded path to JAVA_HOME has been changed on Ubuntu VMs in DevOps.  Removing export to JAVA_HOME from the build script with expectation that user should have set up build environment during installation.
> fix(build): remove export JAVA_HOME in linux build script

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubBadFormatException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubBadGatewayException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubDeviceMaximumQueueDepthExceededException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubDeviceNotFoundException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubGatewayTimeoutException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubInternalServerErrorException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubInvalidOperationException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubMessageTooLargeException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubNotFoundException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubNotSupportedException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubPreconditionFailedException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubServerBusyException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubTooManyDevicesException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubTooManyRequestsException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubUnathorizedException.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/exceptions/IotHubExceptionManagerTest.java
Additional exception context beyond what the service provided was more confusing than helpful in certain circumstances
fixes #329
The additional exception descriptions that the Java SDK added beyond what the service gave us caused some confusion. Customers preferred just knowing what the service returned.
For service side http exceptions, now they will only contain the details given by the service, rather than adding on some extra assumed context that may be wrong.
> refactor(iot-service): Removing additional implied exception details to http exceptions

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/MethodParser.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ParserUtility.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttConnection.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/Helpers.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/MethodParserTest.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceMethod.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceTwin.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceMethodTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceTwinTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttTest.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethod.java
https://github.com/Azure/azure-iot-sdk-java/issues/334
https://github.com/Azure/azure-iot-sdk-java/issues/378
https://github.com/Azure/azure-iot-sdk-java/issues/334 Device Client connect timeout with MQTT if there are 10~ messages stack on IoT Hub.
https://github.com/Azure/azure-iot-sdk-java/issues/378 DeviceMethodCallback message contains backslashes
https://github.com/Azure/azure-iot-sdk-java/issues/334 Deadlock was cased by sharing the same lock in different threads when subscribe is called. Separating locks helped to avoid deadlock during this process. Next step we should look closer to the sync locks and avoid hold lock during I/O operation. …
> fix(iot-deps, iot-device-client): Fixed #334 and #378

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/SendMessagesCommon.java
crashes caused by asserting from working thread
> fix(iot-e2e): test crashes on Android due to Assertion Error on thread

- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceTwinTest.java
Fix getDeviceTwinResponseWithPropertiesWithMetadataCallsTwinPropertyCallBack ut failure due to intermittent java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile.  Mocking out ParserUtility where ZoneInfoFile class is used to avoid the issue.
> fix(iot-dev): mock ParserUtility in Twin device UT

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionString.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/Message.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MessageProperty.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceOperations.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessaging.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/IotHubConnectionStringTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/MessageTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceOperationsTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessagingTest.java
- readme.md
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/IotHubConnectionStringBuilder.java
This PR is a combination of multiple PRs, to be merged in together
460: fix iothubconnectionstringbuilder to be more thread safe
451: make connection string attributes case insensitive (Hostname, GatewayHostName, etc.)
449: Add creation time utc to message class
> PRs 460, 451, 449

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/twin/QueryTwinTests.java
desired properties for n devices were set, and then immediately queried. Often this test would report only finding 1 or 2 of the expected devices due to some propagation time needed. By adding the delay, the query will be more reliable in finding the full set of expected devices with the expected property
> fix(e2e): Fixed flakey query e2e test

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/DeviceEmulator.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/DeviceTestManager.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/IotHubServicesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/DeviceMethodCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/ProvisioningCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/ReceiveMessagesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/SendMessagesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/TransportClientTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/serviceclient/JobClientTests.java
Methods e2e tests have pretty costly logic in the before methods which is adding roughly 100 minutes of total android test time. Most of it was doing nothing useful (deviceThread instance tied to the device emulator just held onto a thread for some odd reason)
Also removed a lot of Thread.sleep(...) calls that were unnecessary (exhaustive testing of this branch should prove they didn't do anything helpful).
Lastly, removed the inter-test delays. Now that each test spawns up its own iot device, we have a 2 second delay after each device is created anyways, so the intertest delay is redundant now.
With all of these changes, the total android build time for Canary Standard went down from 1:20 to 1:07
> Misc speed improvements to e2e

- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/DeviceRegistrationState.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroup.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollment.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/DeviceRegistrationStateTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollmentTest.java
-Relax all device side validation of registration id, device id, etag, etc. for provisioning
-Took out a useless Thread.sleep(...) in provisioning e2e test flow
> Dps relaxation on registration id

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionString.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/ProvisioningCommon.java
Device clients created using security providers led to some confusion between null and empty string within MQTT layer that caused the SDK to not subscribe to C2D. Fixing the SDK to set the gatewayhost name to null, rather than empty string. Also adding check within MQTT layer to prevent this bug if gateway hostname ends up as empty string again later.
Removing unnecessary delay in provisioning e2e tests, and fixing a timeout logic bug too
> fix(iot-device): Fix issue where provisioned devices don't receive C2D over MQTT

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/TwinConnectionState.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/TwinState.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/RegisterManagerTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinStateTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/DeviceTwinCommon.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinDevice.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinDeviceTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinTest.java
service was sending uppercase "Disconnected" and "Connected" when the SDK was expected lowercase "disconnected" and "connected"
The SDK was missing logic to propagate up this Json field to the DeviceTwinDevice object, too.
> fix(iot-service, deps, e2e): Fix issue where ConnectionState was never propagated up through DeviceTwinDevice object

- device/iot-device-client/pom.xml
JNR Unixsocket version 0.19 did not have arm64 support, which prevented some customers from using custom modules in their edgehub deployments. 0.23 has support for arm64, so I have upgraded our dependency.
> fix(iot-dev): Upgrade JNR unixsocet dependency to fix issue #434

- device/iot-device-client/pom.xml
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- device/iot-device-samples/device-method-sample/pom.xml
- device/iot-device-samples/device-twin-sample/pom.xml
- device/iot-device-samples/file-upload-sample/pom.xml
- device/iot-device-samples/handle-messages/pom.xml
- device/iot-device-samples/module-invoke-method-sample/pom.xml
- device/iot-device-samples/module-method-sample/pom.xml
- device/iot-device-samples/module-twin-sample/pom.xml
- device/iot-device-samples/pom.xml
- device/iot-device-samples/send-event-x509/pom.xml
- device/iot-device-samples/send-event/pom.xml
- device/iot-device-samples/send-receive-module-sample/pom.xml
- device/iot-device-samples/send-receive-sample/pom.xml
- device/iot-device-samples/send-receive-x509-sample/pom.xml
- device/iot-device-samples/send-serialized-event/pom.xml
- device/iot-device-samples/transportclient-sample/pom.xml
- device/pom.xml
- iot-e2e-tests/android/app/build.gradle
- iot-e2e-tests/android/things/build.gradle
- iot-e2e-tests/common/pom.xml
- iot-e2e-tests/edge-e2e/pom.xml
- iot-e2e-tests/jvm/pom.xml
- iot-e2e-tests/pom.xml
- pom.xml
- provisioning/provisioning-samples/provisioning-X509-sample/pom.xml
- provisioning/provisioning-samples/provisioning-symmetrickey-sample/pom.xml
- provisioning/provisioning-samples/provisioning-tpm-sample/pom.xml
•	Upgrade JNR Unixsocket dependency to get new support for arm64 devices to do unix socket communication when creating modules from environment
old
{
"device": "1.17.4",
"service": "1.17.1",
"deps": "0.8.4",
"tpmHsm": "1.1.1",
"x509": "1.1.3",
"provisioning": "1.8.1",
"provisioningDevice": "1.7.1",
"provisioningService": "1.5.2",
"java": "0.25.2"
}
new
{
"device": "1.17.5",
"service": "1.17.1",
"deps": "0.8.4",
"tpmHsm": "1.1.1",
"x509": "1.1.3",
"provisioning": "1.8.1",
"provisioningDevice": "1.7.1",
"provisioningService": "1.5.2",
"java": "0.25.3"
}
> Bump package versions for release on 2019-06-19

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubConflictException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubExceptionManager.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/exceptions/IotHubExceptionManagerTest.java
The service SDK had mappings for all other http status codes to IotHubXYZException, but was missing the mapping for 409 errors
> feat(iot-service): Add mapping for 409 status code to IotHubConflictException

- deps/pom.xml
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnection.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/InternalClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- device/iot-device-samples/pom.xml
- device/iot-device-samples/send-event-with-proxy/pom.xml
- device/iot-device-samples/send-event-with-proxy/src/main/java/samples/com/microsoft/azure/sdk/iot/SendEventWithProxy.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/SendMessagesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/HubTierConnectionTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/errorinjection/SendMessagesErrInjTests.java
Building on earlier work for proxy support for HTTPS, this PR enables AMQPS_WS to communicate over proxies now, too.
A part of this pr is migrating away from maintaining the Websocket layer implementation over proton-j, and instead taking a dependency on the proton-j-extensions jar, which is very similar, but also includes proxy support.
Also adding a simple sample for using proxy when sending telemetry
> Add proxy support for clients using AMQPS_WS

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceTwin.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceAuthentication.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceAuthenticationCBS.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceAuthenticationX509.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceMethods.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceOperations.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceTelemetry.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceTwin.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionDeviceOperation.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionManager.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceTwinTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/InternalClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceAuthenticationCBSTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceAuthenticationTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceAuthenticationX509Test.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceMethodsTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceOperationsTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceTelemetryTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceTwinTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionDeviceOperationTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionManagerTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/provisioning/ProvisioningTests.java
Reactor operations are not thread safe, and need to be done on a reactor exposed thread. This PR fixes the device client so that it no longer does any reactor operations on a non-reactor thread.
Benefits include fixing an issue where calling open on an AMQP device client often failed. Now open is significantly more consistent.
Miscellaneous fixes in this PR include fixing reconnection logic in AMQP to work regardless of if client is multiplexing, subscribed to twin, subscribed to methods, etc.
Also removing openClientWithRetry logic now, since AMQP stack now should be relied on to open a connection without retry
> Fix issue where amqp stack opened links on non reactor threads

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/DeviceEmulator.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/IotHubServicesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/DeviceMethodCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/ProvisioningCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/ReceiveMessagesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/SendMessagesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/FileUploadTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/HubTierConnectionTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/TokenRenewalTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/TransportClientTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/errorinjection/ReceiveMessagesErrInjTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/errorinjection/SendMessagesErrInjTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/telemetry/ReceiveMessagesTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/telemetry/SendMessagesTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/twin/DeviceTwinWithVersionTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/provisioning/ProvisioningTests.java
- iot-e2e-tests/edge-e2e/src/main/java/glue/ModuleGlue.java
With Amqp fixes to the open logic, e2e tests no longer need any sort of retry logic for the open calls.
Intertest delays were set to 0 anyways, so all references to them have now been removed
Ensured that e2e test tear down code cannot cause the test it is tearing down to fail
> Remove open with retry in test logic and remove dead code

- vsts/android_java.cmd
mvn install could be sped up by a minute or two with this small change
> refactor(vsts): Parallelize mvn install during android build

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/exceptions/AmqpLinkDetachForcedException.java
- Set AmqpLinkDetachForcedException  as a retryable exception
> Set AmqpLinkDetachForcedException as retryable

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Configuration.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/ConfigurationTest.java
Issue #600 pointed out that the SDK does not allow users to set the configuration metrics on a configuration object. Other SDK's do allow this, so this PR is bringing the SDK up to par.
> feat(iot-serv): Allow ConfigurationMetrics to be set on Configuration objects

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FileUploadNotificationReceiver.java
All receive operations have a QoS of 1, but that wasn't documented before
> doc(iot-serv): Add documentation to fileuploadNotificationReceiver about QoS

- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
Currently, there is a bug where Hosted VS2017 agents fail to run the app center test task. Migrating to use a Mac agent instead mitigates this issue
https://github.com/microsoft/azure-pipelines-tasks/issues/11757
This task didn't really need to be on a Windows machine. It is just making HTTP requests to app center over and over until the tests complete. Mac is good enough to do that, too
Had to change the backslashes to forward slashes because Mac's use forward slashes for directory navigation
> fix(vsts): Fix issue where android test could not be run in azure devops

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/CustomLogger.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionDeviceOperation.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionManager.java
- device/iot-device-samples/module-method-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleMethodSample.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/IotHubServicesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/SSLContextBuilder.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/Tools.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/X509CertificateGenerator.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothubservices/TokenRenewalTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/provisioning/ProvisioningTests.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqtt.java
- service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ConfigurationManangerSample.java
- service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerSample.java
- service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerX509Sample.java
- service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleManagerSample.java
- service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java
There are a number of javadoc issues that prevent successful GH-pages autogeneration. This PR fixes all outstanding issues
> doc(device, e2e, prov-dev, service, samples): Fix javadoc issues

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/Property.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceTwin/PropertyTest.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Pair.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/PairTest.java
$ character is used in digital twin communication, so the device client should not do this validation anymore. Service client is updated to reflect that too.
> fix(iot-serv, iot-dev): Remove SDK side validation of reported and desired properties

- pom.xml
- provisioning/security/tpm-provider/pom.xml
release pipeline works best if the property name is the same as the artifactId but with "-version" suffix
Also tpm hsm is redundant
> fix(pom): Fix issue where tpm-provider pom used version property tpm-hsm

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-samples/provisioning-X509-sample/pom.xml
- provisioning/provisioning-samples/provisioning-symmetrickey-sample/pom.xml
- provisioning/provisioning-samples/provisioning-tpm-sample/pom.xml
- provisioning/provisioning-samples/service-bulkoperation-sample/pom.xml
- provisioning/provisioning-samples/service-enrollment-group-sample/pom.xml
- provisioning/provisioning-samples/service-enrollment-sample/pom.xml
- provisioning/provisioning-samples/service-update-enrollment-sample/pom.xml
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- vsts/sdl.yaml
By flattening the pom files, dependencies declared in parent poms are brought down to children poms. Similarly, property values declared in parent poms are propagated down into the children poms.
As a result, the generated pom files for each published jar (device client, service client, deps, etc.) contain no parent declaration, but inherit all the properties and dependencies that the parent brought
Also, David noticed a provisioning sample that declared the wrong group id, so I'm removing the groupId from each provisioning sample so this isn't a issue moving forward
> Fix pom structures for preview release

- pom.xml
- provisioning/provisioning-samples/provisioning-X509-sample/pom.xml
- provisioning/provisioning-samples/provisioning-symmetrickey-sample/pom.xml
- provisioning/provisioning-samples/provisioning-tpm-sample/pom.xml
- provisioning/provisioning-samples/service-bulkoperation-sample/pom.xml
- provisioning/provisioning-samples/service-enrollment-group-sample/pom.xml
- provisioning/provisioning-samples/service-enrollment-sample/pom.xml
- provisioning/provisioning-samples/service-update-enrollment-sample/pom.xml
- provisioning/provisioning-tools/provisioning-x509-cert-generator/pom.xml
- vsts/sdl.yaml
TSA upload task fixed by changing "Production" to "PROD". This was a breaking change made underneath us, not by something we checked in
Provisioning samples can just inherit the groupId, no need to declare it in each sample. The bulk operation sample even had the wrong groupId because of this
Add maven flatten plugin to base pom so that release pipeline only puts out flat poms with no parents, and with all inherited properties, plugins, and dependencies.
> Fix SDL build, flatten maven poms, fix provisioning samples groupId

- doc/java-devbox-setup.md
Now that Oracle hides JDK 8 from download, we should direct users towards the official Microsoft page dedicated to JDK downloads
> Update java-devbox-setup.md with correct JDK download link

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
•	 Add constructor for Device and Module client that takes SSLContext (#578)
•	 Add additional log statements within the AMQP layer
**Bug Fixes**
•	 Remove device side validation of twin key value pairs
•	 Fix bug where AmqpLinkDetachForcedException was not categorized as retryable
•	 Add API to set configuration metrics on Configuration instance
**Bug Fixes**
•	 Remove device side validation of twin key value pairs
#604, #610, #616, #617, #618, #619, #621, #622, #623, #626, #627, #626, #629, #630
Maven packages
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.19.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/1.19.0/jar
> Bump package versions for release on 2019-12-3

- digital-twin/device/pom.xml
- digital-twin/service/pom.xml
Pom files needed to be configured to output all four necessary artifacts for the release process. Before, they only produced the pom and the base jar
> Fix digital twin device/service poms to build javadoc and sources jars

- deps/pom.xml
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpsConnection.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/ErrorLoggingBaseHandler.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/ProtonJExceptionParser.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/amqp/ErrorLoggingBaseHandlerTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/amqp/ProtonJExceptionParserTest.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
Created an Error Logging Base Handler class that all amqp connections will eventually extend from. It's purpose is to log whenever a link/session/connection is closed remotely (generally considered an error case) or when a transport error occurs.
The deps amqp layer is used only by provisioning device client currently, but this PR makes the device client use it, too. IoT Service client will use it soon when the v2 changes come.
> Refactor Device client and Deps amqp layers to add better error logging

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/helpers/X509CertificateGenerator.java
e2e tests have failed occasionally with service complaining that the test "cert is not valid yet." The certs were created on the fly and were set to be valid immediately, but this issue still occurs probably due to clock skew. Making the test certs valid starting 24 hours prior to when they were generated to avoid this issue.
> refactor(e2e): Make e2e test certs valid in the past

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/HttpHsmSignatureProvider.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/HttpsHsmClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/HttpsRequestResponseSerializer.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsRequest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/hsm/HttpsHsmClientTest.java
- iot-e2e-tests/edge-e2e/src/main/java/glue/ModuleGlue.java
setting the factory handler sometimes failed if this library was used alongside other libraries that set the same handler because that handler can only be set once per jvm session.
Most notably, customers trying to use this library alongside springboot would see failures when creating modules from environment as in #274 
Thankfully, we never really needed to set the urlStreamFactoryHandler for our createFromEnvironment flow. It was just one of a few options, so I have altered the code in question avoid it.
> fix(iot-dev): Fix module client so it doesn't need to set urlStreamFactoryHandler

- deps/pom.xml
- device/iot-device-client/pom.xml
- device/iot-device-samples/pom.xml
- iot-e2e-tests/common/pom.xml
- iot-e2e-tests/edge-e2e/pom.xml
- iot-e2e-tests/jvm/pom.xml
- pom.xml
- provisioning/provisioning-device-client/pom.xml
- provisioning/provisioning-samples/provisioning-X509-sample/pom.xml
- provisioning/provisioning-samples/provisioning-symmetrickey-sample/pom.xml
- provisioning/provisioning-samples/provisioning-tpm-sample/pom.xml
- provisioning/provisioning-samples/service-bulkoperation-sample/pom.xml
- provisioning/provisioning-samples/service-enrollment-group-sample/pom.xml
- provisioning/provisioning-samples/service-enrollment-sample/pom.xml
- provisioning/provisioning-samples/service-update-enrollment-sample/pom.xml
- provisioning/provisioning-service-client/pom.xml
- provisioning/provisioning-tools/provisioning-x509-cert-generator/pom.xml
- provisioning/security/dice-provider-emulator/pom.xml
- provisioning/security/dice-provider/pom.xml
- provisioning/security/security-provider/pom.xml
- provisioning/security/tpm-provider-emulator/pom.xml
- provisioning/security/tpm-provider/pom.xml
- provisioning/security/x509-provider/pom.xml
- service/iot-service-client/pom.xml
- service/iot-service-samples/pom.xml
Edge e2e tests need this change so that it can avoid declaring dependencies on preview vs. non-preview device and service client
> refactor(pom): Factor out published artifactids into master pom

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
**Bug Fixes**
•	 Extend error logging base handler for device client
•	 Fix module client so it doesn't need to set urlStreamFactoryHandler
**Bug Fixes**
•	 Add error logging base handler for amqp connections
•	 Upgrade bouncy castle dependency to latest version (1.64)
#662, #679, #643
> Bump package versions for release on 2020-01-23

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/TokenRenewalTests.java
test sometimes fails with case that mqtt connection never lost connection to hub. This implied that the test didn't wait long enough before checking that the grace period had ended. Adding more buffer time to ensure that the grace period ends before we check that mqtt connection was lost
> refactor(e2e): Adjust timing in token renewal tests

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ExportImportDeviceParser.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ParserUtility.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinParser.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinProperty.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/TwinTags.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/twin/TwinCollection.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/ParserUtilityTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/twin/TwinCollectionTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/twin/DesiredPropertiesTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/twin/TwinTagsTests.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/TwinCollection.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/TwinCollectionTest.java
Twin depth limits may be arbitrarily changed by services, so there is no reason to validate them on the SDK side. It happened once already when the Iot Hub's max depth went from 5 to 10, and the SDK became inconsistent.
Fixes issue #699
> fix(deps, prov-service): Remove SDK-side validation of max twin depth

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
(Note that this release is after an LTS release, so all bumped versions are minor bumps)
**Bug Fixes**
•	Removed SDK side validation of max twin depth (#699)
**Bug Fixes**
•	Removed SDK side validation of max twin depth (#699)
**Bug Fixes**
•	Removed SDK side validation of max twin depth (#699)
**Bug Fixes**
•	Removed SDK side validation of max twin depth (#699)
#703
Maven packages
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.12.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/1.12.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-deps/0.9.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-service-client/1.6.0/jar
> release(2020-02-11): bump package versions

- device/iot-device-client/devdoc/requirement_docs/com/microsoft/azure/iothub/retryPolicy.md
- device/iot-device-client/devdoc/requirement_docs/com/microsoft/azure/iothub/transport/transportExceptions.md
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/exceptions/AmqpLinkMessageSizeExceededException.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/exceptions/AmqpSessionErrantLinkException.java
- device/iot-device-samples/device-reconnection-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceClientManagerSample.java
Currently, the SDK is following the below logic for retrying transport exceptions:
|Exception Name |Error code (if available) |isRetryable  |Action                 |
|------|------|------|------|
| TransportException | | No | Unrecognized transport exceptions are not retried. Inspect the throwable for additional details|
| ProtocolException | | No | Unrecognized protocol exceptions are not retried. Inspect the throwable for additional details|
| IotHubServiceException | | No | Thrown when the Service returns an Unknown Status Code; contact CSS with logs and Exception details |
| BadFormatException | | No | Thrown when service receives a Bad Request; inspect the request being sent |
| HubOrDeviceIdNotFoundException | | No | Inspect the exception details and verify that device/ IoT Hub …
> Update Amqp Exceptions retry logic

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/ProxiedSSLSocket.java
Sending a connect request with http version 1.1 to a server may result in server responded with a 1.0 response. SDK used to require 1.1 response, but there is no practical difference to the SDK whether we get 1.0 or 1.1, so the SDK should ignore this response version
Fixes #715
> fix(iot-device): Allow http proxy to work over http 1.0

- vsts/determine_tests_to_run.ps1
changes to deps pom.xml should force run of iothub and provisioning, for instance
Changes made to vsts pipeline should force all tests to be run, considering that possible changes to that folder include environment variable mistakes
> fix(vsts): Make pom.xml count as package changes

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
**Bug Fixes**
•	 Adjust which amqp exceptions are retryable to improve retry logic
•	 Fix bug where device client using mqtt_ws failed to tunnel through http proxy if proxy response used Http/1.0 (#715)
•	 Added better logging to feedback receiver, cloud to device sender, and file upload notification receiver
**Bug Fixes**
•	 Fixed bug where file upload notification receiver did not clean up its sockets if connection failed (#549)
•	 Fixed bug where file upload notification receiver and feedback receiver both silently swallowed messages occasionally (#720)
•	 Add better logging to amqp layer, and better cleanup logic for error cases
•	 Upgrade qpid proton-j extensions library to latest version
•	 Add better logging to amqp layer, and better cleanup logic for error cases
#716, #717, #713, …
> Bump package versions for release on 2020-02-20

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Enables new security functionality to specify how hub should authenticate when working with a storage account when running import/export devices jobs. Initially, this feature has limited availability, starting with 3 public cloud Azure regions. Since it is not yet widely available, this functionality must be explicitly enabled by the user. See below (1) for details.
- New property `JobProperties.StorageAuthenticationType` for use in import/export devices jobs.
- Added overloaded methods: `RegistryManager.importDevicesAsync`, `RegistryManager.importDevices`, `RegistryManager.exportDevicesAsync` and `RegistryManager.exportDevices`. The overloads take a `JobProperties` instance so the user can pass all required and any optional parameters.
- Two factory methods to make it easier to call …
> Bump package versions for release on 2020-03-13

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsRequest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnectionTest.java
[HTTP plaintext communication Java SDK](https://msazure.visualstudio.com/One/_workitems/edit/5867818)
IoT Hub Java SDK allows unencrypted (HTTP) communication within an https constructor
We will not accept an HTTP method in an HTTPS connection constructor
> Do not accept HTTP urls in Https connection constructor

- vsts/determine_tests_to_run.ps1
The common code did not follow the path "iot-e2e-tests/common/helpers" but rather "iot-e2e-tests/common/src/..."
> fix(vsts): Fix smart gate not recognizing changes to e2e helper code

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MessageProperty.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessaging.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/MessagePropertyTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceMethodsTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceTelemetryTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceTwinTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/telemetry/SendMessagesTests.java
Normally the SDK wouldn't validate something like this, but if a user tries to send an application property with an invalid character in it, the different protocols react in different and unintuitive ways. MQTT will sever the connection with no error message while AMQPS and HTTPS will allow it.
I'm also taking this opportunity to fix a hack tied to URL encoding. URLEncoder doesn't handle encoding spaces correctly, but URIUtil from apache commons does
Lastly, the application property key should be encoded just like the value is when using mqtt, so I've fixed that too
fixes #724
> fix(iot-device): Fix issue where SDK didn't validate application properties correctly

- device/iot-device-samples/android-sample/app/build.gradle
The Azure storage service has separate SDKs for Android Java and regular Java, so this sample needs to use the Android SDK and exclude the normal Java SDK.
Also, this sample needs to manually include apache commons as outlined in issue #519
fixes #684 and #519
> Fix android sample's file upload issue

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpDeviceOperations.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpListener.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpsConnection.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpConnectionTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpDeviceOperationsTest.java
- provisioning/provisioning-device-client/pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/ProvisioningDeviceClient.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/amqp/ProvisioningAmqpOperations.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/http/ContractAPIHttp.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqtt.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/exceptions/ProvisioningDeviceClientExceptionManager.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/ProvisioningTask.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RegisterTask.java
- provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/amqp/ProvisioningAmqpOperationsTest.java
Also fixing an issue where provisioning device client didn't propagate up the error code if an http exception was returned from service
Also fixing a bug where if the provisioning device client ignored amqp messages getting rejected from service. Now the sdk responds and throws appropriately
> refactor(prov-dev, deps): Add better logging to provisioning device client

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
old
{
"device": "1.20.2",
"service": "1.21.0",
"deps": "0.9.2",
"provisioningDevice": "1.8.1",
"provisioningService": "1.6.1"
}
new
{
"device": "1.20.3",
"service": "1.21.1",
"deps": "0.9.3",
"provisioningDevice": "1.8.2",
"provisioningService": "1.6.1"
}
- Improve API documentation for key-based authentication for jobs APIs
- Add support for CA signed X509 over MQTT_WS, and HTTPS
- Fix incorrect logging in AMQP session manager (#730)
- Fix issue where SDK didn't validate application properties in Messages properly
- Add better …
> release(2020-03-30): bump package versions

- iot-e2e-tests/edge-e2e/pom.xml
This change fixed a known code execution vulnerability in Swagger parser. Ran the Snyk tool before and after the change to ensure vulnerability fix.
> fix(e2e): Upgrade swagger-parser to 1.0.50

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/InternalClientTest.java
https://github.com/Azure/azure-iot-sdk-java/issues/739
The SDK needs a way to allow users to configure the receive interval for their connection oriented protocols (MQTT and AMQP)
We will expose a new option name that specifically calls out receive interval on the internal client.
> fix(iot-device):Introduce a new option for receive interval

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClientConfig.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsRequest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientConfigTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/InternalClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsRequestTest.java
Customer's don't like how we originally hard coded the read timeout to 4 minutes, so let's make these levers available to the customer. This PR does not change the default behavior of the SDK, but it does allow users to set new values for the read and connect timeouts
> feat(iot-dev): Add setOption API for setting https request read and connect timeouts

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- Add setOption API setting https read and connect timeouts ("SetHttpsReadTimeout", "SetHttpsConnectTimeout")
- Add setOption API setting how frequently the SDK spawns threads to handle incoming messages ("SetReceiveInterval")
Pull Requests
#755, #752
old
{
"device": "1.20.3",
"service": "1.21.1",
"deps": "0.9.3",
"provisioningDevice": "1.8.2",
"provisioningService": "1.6.1"
}
new
{
"device": "1.21.0",
"service": "1.21.1",
"deps": "0.9.3",
"provisioningDevice": "1.8.2",
"provisioningService": "1.6.1"
}
> release(2020-04-14): bump package versions

- doc/java-devbox-setup.md
We don't have the shade plugin anymore, so this set of instructions shouldn't suggest that the compiled jars contain all dependencies
See #265
> doc(all): Fix java devbox setup instructions

- CODEOWNERS
Adding the team members to the code owners
> fix(docs): Add the team as the owners to the code base

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
Worked for module clients, but not for device clients
> fix(iot-dev): Fix issue with setOption for setting https settings

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- Fix bug where setOption API for setting https read and connect timeouts ("SetHttpsReadTimeout", "SetHttpsConnectTimeout") threw an exception
Pull Requests
#762
old
{
"device": "1.21.0",
"service": "1.21.1",
"deps": "0.9.3",
"provisioningDevice": "1.8.2",
"provisioningService": "1.6.1"
}
new
{
"device": "1.21.1",
"service": "1.21.1",
"deps": "0.9.3",
"provisioningDevice": "1.8.2",
"provisioningService": "1.6.1"
}
> release(2020-04-22): bump package versions

- deps/pom.xml
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/setup/iothub/SendMessagesCommon.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/telemetry/SendMessagesTests.java
Max IoT Hub messsage size is 256 kb, so this is still a bug that you can only send 16 kb, but this is a good incremental change that will benefit customers
related to issue #742, but does not completely solve that issue. We'll need to continue investigating why amqps_ws still cannot send 256 kb messages
> fix(iot-dev): Fix bug in amqpws, raise max message size from 1 kb to 16 kb

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/serviceclient/RegistryManagerTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/http/HttpConnection.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/http/HttpRequest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/RegistryManagerTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/http/HttpConnectionTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/http/HttpsRequestTest.java
Not for service client, just for registry manager
see #766
> feat(iot-service): Add proxy support for registry manager

- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/serviceclient/RegistryManagerTests.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/serviceclient/ServiceClientTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FeedbackReceiver.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FileUploadNotificationReceiver.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ProxyOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManagerOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClientOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpConnectionHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFeedbackReceivedHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceive.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceivedHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpReceive.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSend.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendHandler.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/FileUploadNotificationReceiverTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/RegistryManagerTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/ServiceClientTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFeedbackReceivedHandlerTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceivedHandlerTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendHandlerTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendTest.java
Now that registryManager has proxy support, this PR adds proxy support to the AMQP side of the service client, too.
> feat(iot-service): Add proxy support for service client operations

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MessageProperty.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessaging.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/MessagePropertyTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/telemetry/SendMessagesTests.java
URLEncoder.Encode encodes the space character ' ' as '+' instead of the expected '%20', so I've added a manual replace step for this character. This is most important for MQTT because that protocol doesn't allow topic strings with the '+' character
Also removing all character validation for application property keys and values now that this MQTT bug is fixed. There is no longer a device-side reason to validate these values as all protocols are encoding them correctly now such that the protocol doesn't throw an exception. Iot Hub will be the validator, not the client.
Hub does allow these previously banned characters, provided they are encoded correctly for each protocol.
> fix(iot-dev): Fix issue where MQTT didn't url encode application properties correctly

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsDeviceOperations.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionDeviceOperation.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionManager.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/SubscriptionMessageRequestSentCallback.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionDeviceOperationTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionManagerTest.java
The recent twin array support changes introduced sending a desired properties subscription message each time the twin sender link opened. However, once the service acknowledges that message, our SDK logged an exception as it didn't correlate the ack back to the subscription message it sent. This PR adds a callback so that the top AMQP layer can be notified each time a lower level sends a subscription message
> fix(iot-dev): Fix issue where amqp layer didn't recognize an ack to a subscription message that it sent

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
This was missing from the list of options, even though it is a valid option that users can set
> doc(iot-dev): Add missing javadoc explaining SetSendInterval for setOption API

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
See #772 
Customer's need a bit more help understanding how startDeviceTwin works, so I've beefed up the javadocs for it
> doc(iot-dev): Add clarification to startDeviceTwin() API docs

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ErrorCodeDescription.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ErrorMessageParser.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/ErrorMessageParserTest.java
- iot-e2e-tests/common/src/main/java/com/microsoft/azure/sdk/iot/common/tests/iothub/methods/DeviceMethodTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubBadFormatException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubBadGatewayException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubConflictException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubDeviceMaximumQueueDepthExceededException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubDeviceNotFoundException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubExceptionManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubGatewayTimeoutException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubInternalServerErrorException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubInvalidOperationException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubMessageTooLargeException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubNotFoundException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubNotSupportedException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubPreconditionFailedException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubServerBusyException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubTooManyDevicesException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubTooManyRequestsException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/exceptions/IotHubUnathorizedException.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendHandler.java
Previously, the service client ignored the fully qualified status codes embedded in the error message for cases where the service threw a 404/500/etc.
Customer's need to have some granularity in treating a 404001 (deviceNotFound) from a 404010 (moduleNotFound) from a 404103 (deviceNotOnline) as these are all potential error cases when invoking a method on a module.
Now all of our service side exception types have dedicated fields for error code and error code description.
The error code will be the 6 digit code (404001, for instance) if the service gave the SDK that code, or it will be the 3 digit error code that we always get in the http response object (404, for instance)
> Add support for fully qualified error codes in service client HTTP exceptions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/Message.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/MessageTest.java
During this conversion, the simple date formatter assumed local time, when it should be using UTC time
> fix(iot-device): Fix issue where creationTimeUTC used local timezone during stringification

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/IotHubConnectionString.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/JobProperties.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
This API version was only available in certain regions previously, but now that it is available in every region, we can make all service client operations use this
We can also get rid of the environment variable lookup that was previously used to toggle between a widely available service API version and the selectively available service api version
> refactor(iot-service): Make all service operations use the latest service api version

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Make all service client APIs use new Service API Version (#788)
- Add support for fully qualified error codes in service client HTTP exceptions (#782)
- Add Client Options to enable users to supply model id on MQTT (#791)
**Bug Fixes:**
- Fix issue where creationTimeUTC used local timezone during stringification (#784)
- Add support for fully qualified error codes in service client HTTP exceptions (#782)
> release(2020-06-12): bump package versions

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManagerOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/http/HttpConnection.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/http/HttpRequest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/RegistryManagerTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/http/HttpConnectionTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/transport/http/HttpsRequestTest.java
Adding them to the RegistryManagerOptions class so that they are set at constructor time
> feat(iot-service): Add support for setting http read and connect timeouts for registry manager operations

- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/FileUploadAndroidRunner.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/FileUploadTests.java
Simplifying the data structure used to collect file upload notifications. Also removing the file upload notification listener thread. Each test can open their own amqp connection to get file upload notifications as long as they all put those notifications in the shared data structure.
These tests can still be run in parallel, but cannot be run at the same time in two different test processes. This is how they were before, though.
> refactor(e2e): Simplify file upload tests, re-enable file upload tests on android

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TransportClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
The twin service client can be relegated to the test instance. Having a static instance was causing issues as it was sometimes prematurely disposed and would cause the NPE in a different thread.
> fix(e2e): Fix issue where transport client twin tests sometimes threw a null pointer exception

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TransportClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
A lot of scenarios had a 3 second timeout which is rather strict. Opening that timeout up to 1 minute so that the test isn't as flakey
> Fix flakey twin e2e tests

- iot-e2e-tests/common/pom.xml
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTPMTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
~~Two small e2e test changes~~. The TPM tests need to run in serial since they each need exclusive access to the tpm simulator in order to pass.
~~The twin tear down logic should never throw an exception that causes the test to fail since the teardown logic is part of what's being tested~~
> Run TPM tests in serial

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubReceiveTask.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubSendTask.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceIOTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubReceiveTaskTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubSendTaskTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
The current design of the device client library periodically spawns threads to handle sending and receiving messages as well as invoking callbacks. The device client will spawn these threads regardless of if any messages actually need to be sent/received, though.
With this change, the send/receive threads will instead wait until a message requires them to wake up. This will cut down on thread creation during less busy times without sacrificing performance during busy times
The second commit for this PR makes our DeviceIO layer more responsive to connection change events. Previously, if the transport layer went into reconnecting mode, the device IO layer would still spawn send/receive threads repeatedly even though they would be unable to send/receive anything since the transport isn't …
> refactor(iot-dev): Use wait and notify to cut down on useless thread creation in transport layer

- readme.md
Also following the convention that the C# repo has where it is "master" and "preview" instead of "WestUs" and "Canary"
> doc(all): Fix preview build badge not showing up

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceIOTest.java
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
InternalClient methods such as subscribeToTwinDesiredProperties check this ```isOpen()``` method before queueing messages.
The previous behavior was to allow users to queue messages and send subscription messages even when the client is in a reconnecting state.
> fix(iot-dev): Fix issue where clients couldn't queue messages while reconnecting

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/DeviceEmulator.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/DeviceTestManager.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/ErrorInjectionHelper.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/IotHubServicesCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/DesiredPropertiesErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/DeviceMethodErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/GetTwinErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/ReceiveMessagesErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/ReportedPropertiesErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/SendMessagesErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/SendMessagesCommon.java
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
Iot Hub responds to fault injection messages differently for AMQP and MQTT. For AMQP, the fault injection message will be ack'd before the fault takes effect, but this isn't the case for MQTT. To make it more reliable that the fault injection message gets sent, AMQP tests should wait for this FI message to be ack'd. MQTT tests still need to provide an expiry time, but that time has been bumped up from .1 or .2 seconds to 1 second to increase the chances that it gets delivered at least once
> fix(e2e): Fix fault injection message tests

- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/http/ContractAPIHttp.java
- provisioning/provisioning-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/http/ContractAPIHttpTest.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/ContractApiHttp.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/contract/ContractApiHttpTest.java
DPS would occasionally return a 411 error because this wasn't being sent on registration requests and enrollment creations
It doesn't appear to be a hard requirement since tests usually pass without them, but just to be safe we should send them. The 411 failures seem to disappear once this change is made.
> fix(prov-dev, prov-serv): Fix provisioning clients not sending content length with http requests

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
old
{
"device": "1.23.0",
"service": "1.23.0",
"deps": "0.9.5",
"provisioningDevice": "1.8.2",
"provisioningService": "1.6.1"
}
new
{
"device": "1.24.0",
"service": "1.24.0",
"deps": "0.10.0",
"provisioningDevice": "1.8.3",
"provisioningService": "1.6.2"
}
- Add support for setting HTTP read and connect timeouts for registry manager operations (#815)
- Add new File upload APIs for more granular control over the now deprecated file upload API (#808)
- Add PnP ModelId option to ModuleClient constructors
- Deprecated Client …
> release(2020-07-07): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
old
{
"device": "1.0.1",
"service": "1.0.1",
"deps": "1.0.1",
}
new
{
"device": "1.1.0",
"service": "1.1.0",
"deps": "1.1.0",
}
- Add PnP Summer refresh model Id support
- Make http read and connect timeouts configurable for registry manager operations
- Add proxy support for registry manager and service client operations
- Add support for fully qualified error codes when provided by service
- Add twin array support
- Add support for identity based storage authentication for jobs
- Brought all bug fixes in from iot-service-client:1:24:0
- Add PnP Summer refresh model Id support
- Stabilize AMQP layer with several bug fixes
- Fixed several performance issues
- Deprecate file upload APIs in favor of new, more granular APIs to allow for users to choose their Storage SDK dependency
- Fixed …
> release(2020-07-08): bump preview package versions

- iot-e2e-tests/common/src/test/resources/log4j.properties
While system.out will get very busy thanks to our tests running in parallel, Azure Devops is smart enough to allow you to view the logs for each individual test run without other test run's logs getting in the mix.
We'll need this level of logging in place to understand the recent transient issues that we've been seeing and haven't been able to reproduce
> refactor(e2e): Add sdk logging to all test runs

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
If two messages are queued, one for subscribing to twin, and one for getting a twin, and the latter is queued first, then the SDK gets stuck trying to send the get twin request repeatedly without trying to send the subscribe message first.
This change ensures that any message that fails to send is placed at the back of the queue and that the next message stays at the front of the queue. This helps to protect the SDK from states where some messages need to be sent before others, but never are
One of our edge e2e tests was occasionally failing due to this bug.
> fix(iot-dev): Fix issue with ordering of queue within amqp layer

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnectionTest.java
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
It spawned no threads and wasn't used anywhere, so it should be removed
> refactor(iot-dev): Remove unused executor service

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/QueryTwinTests.java
Now every query test will re-run the query until the expected conditions are met or a timeout occurs. This helps to account for any propagation delays on the service side between device creation and when the device is queryable.
By inheriting from DeviceTwinCommon, each query test was run for every device side protocol and for every device side authentication. These query tests are entirely service client tests, though. It doesn't make sense to parameterize them on device client settings
> refactor(e2e): Fix query tests

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
The difference between scheduleAtFixedRate and scheduleWithFixedDelay is that the former will attempt to queue new threads even when the previous send/receive thread is not done yet. Now that our SDK has these send/receive threads wait to be notified when a message is ready to be sent/received, we don't want to try to schedule new threads every X milliseconds regardless of previous thread completion. We want to schedule a new thread every X milliseconds after the previous thread has completed
> refactor(iot-dev): Change thread scheduling pattern in deviceIO layer

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/DeviceEmulator.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/DeviceTestManager.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/DeviceMethodErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/methods/DeviceMethodTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/JobClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceMethodCommon.java
Each deviceMethods client only allows one method invocation at a time, but some tests deliberately have the method invocation take multiple seconds. This commit splits the static device method client so that each test instance has its own direct method client instead. That minimizes any cross-test interference that the above synchronization could cause. Note that I suspect this is one of the possible causes of the device method test timeouts that we've been seeing lately.
Fixed the device method tests not waiting for the methods subscription message to be acknowledged on the device before invoking the method
Previously test setup always created and opened a device client instance regardless of if the test actually needs it. Now that setup is opt-in with a call to …
> refactor(e2e): Reduce unnecessary operations, simplify setup/teardown for methods tests

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/IntegrationTest.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/Tools.java
- iot-e2e-tests/common/src/test/resources/log4j.properties
log4j.properties doesn't recurse with star notation, it just recurses in this notation
The start/stop logs should be to our logger, not system.out. That way we get the logger timestamp for free on these two logs
> fix(e2e): Fix small logging issues

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceMethodCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/ReceiveMessagesCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/SendMessagesCommon.java
SAS and x509 device were created for each method/c2d/d2c regardless of if the test was for SAS or x509. Since registry operations are becoming a bottleneck in our tests, we need to clean these up
> refactor(e2e): Remove unnecessary identity registry operations

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/RegistryManagerTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java
These tests are timing out since they rely on registry manager operations which may take a while to execute since only one thread can do a registry manager operation at a time and most tests need to do at least one registry manager operation.
For instance: https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=65369&view=ms.vss-test-web.build-test-results-tab&runId=1579266&resultId=103226&paneView=debug
> refactor(e2e): Remove shorter, test specific timeouts

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
Currently we use ProvisioningServiceClient instance declared publicly for all provisioning tests, moving this set up under test Instance per test.
> refactor(e2e): Simplifying provisioning service client setup

- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
This is useful if you run a pipeline once, it fails on some tests, you rerun the job, and it fails again. With this change, you can correlate the test results drop down with the rerun #
> refactor(vsts): Add retry count to test results title in Azure Devops

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnection.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnectionTest.java
This same logic took place at the IotHubTransport layer based on the result of this method call, so no need to include this logic in the HTTP layer
You can see this logic here:
https://github.com/Azure/azure-iot-sdk-java/blob/5867a9311ec7f30102e37106b3a26ec7f769c802/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java#L1026
> fix(iot-dev): Fix issue where errors encountered at http message level were handled twice

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
All notify calls must be wrapped in synchronization blocks on the object that will be notified. Otherwise the notify call will throw an IllegalMonitorStateException and won't wake up the send thread as expected.
This PR just adds that synchronization block so that when the message is requeued, it will wake up the send thread
> fix(iot-dev): Fix issue where notfiy call was not wrapped by synchronization block

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
There is some propagation delay between when a device is provisioned to a hub and when it is queryable. This commit refactors the test to just query for the device until it can be found, rather than just query once and hope the device was ready to be queried.
> fix(e2e): Fix timing issue in provisioning e2e tests

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsCbsSessionHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsLinkStateCallback.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSenderLinkHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionStateCallback.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
fixes issue #887 
If the delivery state was anything other than Accepted, the SDK needs to either retry sending the message or bubble up that exception to the user
> fix(iot-dev): Fix issue where amqp layer ignored delivery state of sent messages

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
old
{
"device": "1.24.0",
"service": "1.24.0",
"deps": "0.10.0",
"provisioningDevice": "1.8.3",
"provisioningService": "1.6.2"
}
new
{
"device": "1.25.0",
"service": "1.25.0",
"deps": "0.10.0",
"provisioningDevice": "1.8.3",
"provisioningService": "1.6.2"
}
- #890 Fix charset bug in IotHubServiceSasToken buildToken method. 
- #889 Add support for batch event messages for HTTPS protocol.
- #888 Fix issue where amqp layer ignored delivery state of sent messages
- #891 Fix issue where errors encountered at http message level were …
> release(2020-08-13): bump package versions

- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/errorinjection/twin/DesiredPropertiesErrInjAndroidRunner.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/errorinjection/twin/GetTwinErrInjAndroidRunner.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/errorinjection/twin/ReportedPropertiesErrInjAndroidRunner.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/twin/DesiredPropertiesAndroidRunner.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/twin/GetTwinAndroidRunner.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/twin/QueryTwinAndroidRunner.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/twin/ReportedPropertiesAndroidRunner.java
- iot-e2e-tests/android/app/src/androidTest/java/com/microsoft/azure/sdk/iot/android/iothub/twin/TwinTagsAndroidRunner.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/DesiredPropertiesErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/GetTwinErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/ReportedPropertiesErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/methods/DeviceMethodTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/DesiredPropertiesTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/GetTwinTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/QueryTwinTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/ReportedPropertiesTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/TwinTagsTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethod.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethodClientOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceOperations.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinClientOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Query.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollection.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethodTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollectionTest.java
Basically the same as how the registry manager takes these options.
Making the read/connect timeouts configurable will help with speeding up our e2e tests, and this is a useful feature for customers anyways
> feat(iot-serv): Make http connect and read timeouts configurable on twin and methods clients

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/IntegrationTest.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/Tools.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/rules/ThrottleResistantTestRule.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/FileUploadTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/HubTierConnectionTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TokenRenewalTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TransportClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/methods/DeviceMethodTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ExportImportTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/JobClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/RegistryManagerTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceMethodCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/ReceiveMessagesCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/SendMessagesCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/telemetry/ReceiveMessagesTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/DeviceTwinWithVersionTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/QueryTwinTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
This PR removes some unnecessary SDK side bottle necking around adding devices/modules to the registry. See comments below for an explanation on that.
This PR also adds a test rule that watches out for throttling from the service. Now that we are sending more registry requests at once, we are hitting throttling pretty often on S1 hubs in canary and sometimes in S1 hubs in prod. This new test rule basically re-runs any test that fails due to a throw 429 exception. This allows us to generally not care if a test hits a throttling limit or not without implementing retry logic on each service request (which would take a very long time)
This PR also moves some static registry/method/twin clients to live at a per-test-instance level to keep each test more isolated from one another
> refactor(e2e) adding throttling resiliency to tests, allow more registry operations in parallel

- device/pnp-helper/src/main/java/com/microsoft/azure/sdk/iot/pnphelpers/PnpHelper.java
We used incorrect formatting when putting a hyperlink in our javadoc
> doc(pnp-helper): Fix javadoc in PnP Helper

- .gitignore
flattened poms are generated during the javadoc creation process, but we don't want to check them in. Similarly, the javadoc options files aren't relevant enough to commit to this branch. Lastly, the e2e tests folder should be completely ignored since we do not publish any jars from that folder much less any javadocs.
> refactor(javadocs): Add more files to gh-pages gitignore

- .gitignore
- deps/pom.xml
- device/iot-device-client/pom.xml
- provisioning/provisioning-device-client/pom.xml
- provisioning/provisioning-service-client/pom.xml
- provisioning/security/dice-provider-emulator/pom.xml
- provisioning/security/dice-provider/pom.xml
- provisioning/security/security-provider/pom.xml
- provisioning/security/tpm-provider-emulator/pom.xml
- provisioning/security/tpm-provider/pom.xml
- provisioning/security/x509-provider/pom.xml
- service/iot-service-client/pom.xml
- vsts/StartEmulator.sh
- vsts/generate_javadocs_branch.ps1
generateJavadocs.ps1 will generate javadocs for the checked out branch (configurable to master, preview, etc as needed) then create a new branch based on the current gh-pages branch that contains the up to date javadocs. We'll still have to manually create a PR to merge that branch into gh-pages.
TODO is for me to update our internal repo's release notes to include this new step, and to point to the release pipeline that will use this new generateJavadocs.ps1 script. Once this PR is merged in, I'll take care of that
> refactor(vsts): Automate javadoc generation

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSample.java
- device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSimpleSample.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/FileUploadTests.java
completeFileUploadAsync does not behave asynchronously, so the name was a mistake. Deprecating that API and creating a new one without the Async suffix
#910
> feat(iot-dev): Fix file upload complete notification API

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsExceptionTranslator.java
Issue #900 has an example of our AmqpsExceptionTranslator throwing a null pointer when the passed in errorCode is null. This PR adds a null check to that argument to ensure a null pointer isn't thrown there
> fix(iot-dev): Fix possible null pointer issue in amqp layer

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/HttpsHsmClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsRequest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/hsm/HttpsHsmClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsConnectionTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/https/HttpsRequestTest.java
Some edgelet uris are http requests to localhosts, so the SDK needs to support that.
issue #914
> fix(iot-dev): fix issue where edgelet hsm requests did not support http

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientComponentTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/helpers/E2ETestConstants.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinMetadata.java
Add E2E tests other than update
Fixed retrofit error for null payloads
> E2E tests and workaround for retrofit error with null payload

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
release(2020-10-01): bump package versions
old:
{
"device": "1.25.0",
"service": "1.25.0",
"deps": "0.10.0",
"provisioningDevice": "1.8.3",
"provisioningService": "1.6.2"
}
new:
{
"device": "1.26.0",
"service": "1.26.0",
"deps": "0.11.0",
"provisioningDevice": "1.8.4",
"provisioningService": "1.7.0"
}
- Add a new client (DigitalTwinClient) to support operations against Digital Twin. Digital Twin APIs operate on high-level constructs in the Digital Twins Definition Language (DTDL) such as components, properties, and commands. The …
> release(2020-10-01): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClientConfig.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
https://github.com/Azure/azure-iot-sdk-java/issues/906
Adding user configurations for amqp timeouts
> feat(device-client): Add configuration for amqp authentication and device session timeouts

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/IntegrationTest.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceMethodCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/ReceiveMessagesCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/SendMessagesCommon.java
Opening a device client can sometimes fail due to the client taking too long to get a device session or authentication session established. This PR lengthens these timeouts from the restrictive default values.
> refactor(e2e): Add longer amqp open timeouts to device clients in e2e tests

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- pom.xml
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Updated API version for IoTHub service to support plug-and-play features ([#968](https://github.com/Azure/azure-iot-sdk-java/pull/968))
- Add a new client (DigitalTwinClient) to support operations against Digital Twin. Digital Twin APIs operate on high-level constructs in the Digital Twins Definition Language (DTDL) such as components, properties, and commands. The Digital Twin APIs make it easier for solution builders to create IoT Plug and Play solutions. ([#918](https://github.com/Azure/azure-iot-sdk-java/pull/918))
- Make http connect and read timeouts configurable on twin and methods clients ([#878](https://github.com/Azure/azure-iot-sdk-java/pull/878))
- Fix issue where cloud to device messages with no payload would cause NPE when sent …
> release(2020-10-15): bump package versions

- vsts/generate_javadocs_branch.ps1
This script is use in a pipeline to autogenerate the content for java docs. They will not be placed in corresponding master/preview folders. The pipeline will be updated after the change is checked in.
> Fixing script to generate gh-pages in correct folder

- index.html
This update should display links to preview API versions in gh-pages website.
It will look like this - https://vinagesh.github.io/azure-iot-sdk-java/
> feat(javadocs): Adding links to preview APIs

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- Added support for configuring amqp layer timeout values ([#908](https://github.com/Azure/azure-iot-sdk-java/pull/908))
- Fixed bug where provisioning device client URL encoded SAS token URL before signing and after signing ([#990](https://github.com/Azure/azure-iot-sdk-java/pull/990))
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.27.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-device-client/1.8.5/jar
old
{
"device": "1.26.0",
"service": "1.26.0",
"deps": "0.11.0",
"provisioningDevice": "1.8.4",
"provisioningService": "1.7.0"
}
new
{
"device": "1.27.0",
"service": "1.26.0", …
> release(2020-11-16): bump package versions

- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MultiplexingSample.java
This comment is out of date with how the multiplexing client currently handles registrations/unregistrations during active connections
> Fix documentation in multiplexing sample

- vsts/generate_javadocs_branch.ps1
As we have created a new preview branch, all packages have the same version as master and not the latest preview version. This leads to generation of incorrect docs as we have only released a new device-client preview. To ensure that the gh-pages are only updated for the corresponding package, I have added a conditional generation which can be set in the pipeline. This way, we can just generate the required documentation and keep the others ones as is.
This change will go to preview when I merge master to preview.
Pipeline now has the following options. They will be used once this PR is checked in.
> fix(documentation): Adding conditional docs generation

- device/iot-device-samples/multiplexing-sample/pom.xml
- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ClientManagerBase.java
- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ConnectionStatus.java
- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ConnectionStatusTracker.java
- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceClientManager.java
- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MultiplexClientManager.java
- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MultiplexingSample.java
- device/iot-device-samples/multiplexing-sample/src/main/resources/log4j.properties
With this change, `DeviceClientManager `objects will be wrapped around device clients to manage the reconnection logic. 
`DeviceClientManager `and `MultiplexingClientManager `both extend `ClientManagerBase `that hold the core reconnection logic.
All API calls to the `DeviceClientManager `and `MultiplexingClientManager `will be delegated to the client they are wrapping.
> Multiplexing samples: Device Client Manager and Multiplexing client manager

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
Sending a get twin request while the subscribe to desired properties request was in progress seemed to cause reliable NPE in transport clients that start twin for each of their devices. By waiting for the in progress subscriptions to finish before sending actual messages over these links, the NPE goes away. The NPE itself comes from within the AMQP library, so my best guess is that there is a race condition of some sort that we would hit previously
Also simplify some code in our executor service cleanup logic to match what we checked into preview earlier.
> fix(iot-dev): Fix possible NPE in AMQP layer

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- Add client constructors that take SAS token provider interface. #1002
- Fixed some potential NPE exceptions within the AMQP layer's twin subscription logic. #1012
- Add helper function to compute derived symmetric keys for enrollment group registrations. #1001
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.28.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning.security/security-provider/1.4.0/jar
old
{
"device": "1.27.0",
"service": "1.26.0",
"deps": "0.11.0",
"provisioningDevice": "1.8.5",
"provisioningService": "1.7.0"
}
new
{
"device": "1.28.0",
"service": "1.26.0",
"deps": "0.11.0", …
> release(2020-12-04): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
exception should be retryable, and the catch block should close the reactor and shut down the executor service, not just shut down the executor service. Close() covers this well so a call to it from this catch block works well
> fix(iot-dev): Fix cleanup logic in AMQP layer when interrupted during open

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MultiplexingSample.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
If a client subscribes to twin and method, then unregisters from its multiplexing client, and is later re-registered, the default behavior will be to not preserve those subscriptions. We can add an optional parameter to enable this sort of behavior later, if users are interested.
> [Preview] Fix multiplexingClient not allowing re-registered clients to subscribe to twin/methods

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
This loop happens in the AMQP worker thread, so users wouldn't notice this, but it is still a bug.
> fix(iot-dev): Fix issue where unregistering a multiplexed device that isn't registered loops infinitely

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
Closing a session locally before the session was opened remotely causes a NPE to throw from proton with error message "uncorrelated channel: X", so this will fix our session handlers to not close locally before the session has been opened remotely
The relevant proton code can be seen [here](https://github.com/apache/qpid-proton-j/blob/fcdc70521186d626490657823289bd952121f0ce/proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java#L1213).
Note that the proton function in question is a handler function for "session begin" frames sent by the service
> fix(iot-dev): fix issue where AMQP layer sometimes throws "uncorrelated channel" NPE

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- Change exceptions thrown by ```MultiplexingClient``` APIs, add timeout to registration and unregistration API calls
- Add overloaded APIs for registering/unregistering device clients with a custom timeout. #1010
- Add device and module client constructors to take SAS token provider interfaces. #1002
- Fixed some potential NPE exceptions within the AMQP layer's twin subscription logic. #1012
- Fixed issue where AMQP layer sometimes throws "uncorrelated channel" NPE. #1021
- Fixed issue where re-registered multiplexed device clients could not start twin or subscribe to device methods. #1021
- Fixed issue where unregistering an unregistered device cause AMQP worker thread to loop infinitely. #1019
- Fixed cleanup logic in AMQP layer when interrupted during open call. #1015
- Fixed …
> release(2020-12-09): bump package versions

- vsts/generate_javadocs_branch.ps1
Here is an example of the pipeline run - https://github.com/Azure/azure-iot-sdk-java/tree/gh-pages-2020-12-09
I tweaked the pipeline to run off of my branch to get this. If you look in the contents of the branch, only one folder inside master is changed corresponding to the run (because only that was set to true)
> (gh-pages): Fixing script to conditionally generate docs

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
Previously, the local state of which devices were registered already would be incorrect upon encountering an error like this if the error wasn't triggered by the first device client in the list to register.
> fix(iot-dev): Fix multiplexing client so that it unwinds previous bulk registrations if one client isn't supported

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
Only some of the tests were nice enough to clean up their resources after finishing, but now they all will
> refactor(e2e): Make provisioning tests clean up enrollments after test finishes

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FeedbackReceiver.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/FileUploadNotificationReceiver.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClientOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpConnectionHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFeedbackReceivedHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceive.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceivedHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpReceive.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSendHandler.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/FileUploadNotificationReceiverTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/ServiceClientTest.java
This enables users to load their preferred public certificates which is necessary for supporting private Hub environments
#1027 for reference
> feat(iot-service): Add custom SSLContext option to service client construction

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
Cannot start twin after unregistering from a multiplexing client, for example. Some methods like that were just missing the check that verifyRegisteredIfMultiplexing() runs and were throwing NPE when they tried to access the device IO instance
> fix(iot-dev): Add missing checks for multiplexing state before client methods

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TokenRenewalTests.java
Test threw an indexOutOfBounds exception because the list that it tried to get the hostname from was always empty, so the test has been refactored to get the hostname from a different list of clients that is never empty instead
Without this change, the test always fails. The only reason it got like this was because we don't run this test at the gate since it is a 15 minute test
> Fix(e2e) fix e2e test

- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/FileUploadCompletionNotificationTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/FileUploadSasUriRequestTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/FileUploadSasUriResponseTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/serializer/MethodParserTest.java
- deps/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/deps/ws/impl/WebSocketImplTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/IotHubConnectionStringTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenWithRefreshAuthenticationProviderTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/fileupload/FileUploadTaskTest.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/DeviceEmulator.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TransportClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/errorinjection/ReportedPropertiesErrInjTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/JobClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/DeviceTwinCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/ReportedPropertiesTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollmentTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/TwinCollectionTest.java
- provisioning/security/security-provider/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/security/SecurityProviderTpmTest.java
- provisioning/security/security-provider/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/security/SecurityProviderX509Test.java
- provisioning/security/tpm-provider-emulator/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMEmulator.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/jobs/JobResultTest.java
The warning has been suppressed in test classes, since the flagged params were being referenced in helper methods
> [Declaration redundancy] Actual method parameter is the same constant - tests

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Add support for providing custom SSLContext to service client instances (#1044)
- Increase dependency versions for commons-codec, jackson (#1039)
- Add new MultiplexingClient that allows for dynamic adding and removal of devices from a multiplexed connection even after opening the connection, deprecate previous multiplexing client TransportClient (#939)
- Fix cleanup logic in AMQP layer when interrupted during open (#1015)
- Increase dependency versions for commons-codec, jackson (#1039)
- Increase dependency versions for commons-codec, jackson (#1039)
- Increase dependency versions for commons-codec, jackson (#1039)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/1.27.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1 …
> release(2021-01-20): bump package versions

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSend.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/ServiceClientTest.java
The SSLContext wasn't passed all the way down to where it was needed due to some confusion with overloaded constructors
> fix(iot-service): Fix c2d messages not using custom SSLContext when set in service client options

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/ExponentialBackoffWithJitter.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/NoRetry.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/RetryDecision.java
Mirroring the effort done in [Add a log statement to indicate a NoRetry retry policy was enabled](https://github.com/Azure/azure-iot-sdk-csharp/pull/1763) for the csharp SDK.
The ask from the CSS team is as below:
In certain situations customers raise support issues stating that the client does not recover on disconnection, only to discover on inspection of customer code that they have explicitly disabled the inbuilt retry policy in the client.
In order to avoid long delays in identifying the issue, the CSS team wants us to log a statement in case the retry policy is disabled.
This PR adds logging to the following classes `NoRetry`, `ExponentialBackoffWithJitter`, and `RetryDecision` to indicate the creation of the policy or the current decision.
> Add logging to both retry policies and the RetryDecision class

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix service client's cloud to device message sender not using custom SSLContext when set (#1090)
- Add additional logging to retry logic (#1103)
- Fix some log statemnts within transport layer (#1091)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.29.1/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/1.27.1/jar
old
{
"device": "1.29.0",
"service": "1.27.0",
"deps": "0.11.1",
"securityProvider": "1.4.0",
"provisioningDevice": "1.8.6",
"provisioningService": "1.7.1"
}
new
{
"device": "1.29.1",
"service": "1.27.1",
"deps": "0.11.1",
"securityProvider": "1.4.0",
"diceEmulator": …
> release(2021-02-04): bump package versions

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/GetTwinTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/QueryTwinTests.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/Query.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceOperations.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Job.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Query.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollection.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/RawTwinQuery.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceOperationsTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollectionTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/RawTwinQueryTest.java
The twin client and the query clients are very intertwined, so I had to group them together for this PR
> feat(iot-service): Add TokenCredential and AzureSasCredential support to Query and Twin clients

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClientOptions.java
same as other options objects; HTTP read and connect timeouts, and proxy support.
I've seen our nightly builds often fail on http read timeouts on digital twin tests, so this feature should help our tests be more resilient, too
I'm adding this to the RBAC preview code since that is where we are already adding a bunch of digital twin constructors.
> feat(iot-service): Add DigitalTwinClientOptions support to digital twin clients

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttConnection.java
1 second timeout is a bit too short to accommodate when the service is a bit slower due to load. 1 minute is a bit more reasonable
#1123 
https://github.com/Azure/azure-iot-sdk-java/issues/1123#issuecomment-782443807
> fix(deps): Fix MQTT subscribe timeout being 1 second

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/SendMessagesCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/telemetry/SendMessagesTests.java
Before this fix, they could send messages up to 16 kB, but this fix brings the limit in line with the IoT Hub size limits, and makes AMQPS_WS consistent with all other protocols.
For additional context: https://github.com/Azure/azure-iot-sdk-java/issues/742
> fix(iot-device): Fix bug where AMQPS_WS clients couldn't send messages with payloads up to 256 kB

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix potential NPE cases within MQTT layer (#1125)
- Fix AMQPS_WS not being able to send the expected 256 kB payload messages (#1129)
- Bump dependency version of IoT Deps
- Fix bug where mqtt subscribe timeout was only 1 second (#1126)
- Fix bug where mqtt provisioning device client registration could easily time out (#1126)
- Bump dependency version of IoT Deps
- Fix bug where SecurityProviderTpmHsm cleared the TPM's EK and SRK at constructor time (#1128)
old
{
"device": "1.29.1",
"service": "1.27.1",
"deps": "0.11.1",
"securityProvider": "1.4.0",
"provisioningDevice": "1.8.6",
"provisioningService": "1.7.1"
}
new
{
"device": "1.29.2",
"service": "1.27.2",
"deps": "0.11.2", …
> release(2021-02-24): bump package versions

- pom.xml
Bump versions script had a bug in it that caused it to not bump the tpm-provider version. The bug has been fixed in that script, and this commit fixes that issue in the previous version bump commit
> Bump additional version for 2/24/2021 release

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/auth/TokenCredentialCache.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethod.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Query.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollection.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/RawTwinQuery.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobClient.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/auth/TokenCredentialCacheTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceOperationsTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/JobTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollectionTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/QueryTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/jobs/JobClientTest.java
AMQP client doesn't need it since it has proactive renewal in place already.
> refactor(iot-service): Add AAD auth token caching for HTTP clients

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/IotHubReactor.java
reactor.free() releases file descriptors that were grabbed by proton reactor. Since the connection failed to open, there is no need to hang on to them.
#1135 for more context
> fix(iot-dev): Fix bug where AMQP layer doesn't release resources after failing to open

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
continuing on from #1135, this change ensures that even if the AMQP layer encounters an exception while closing manually, that the reactor is always free'd at the end
#1135 for additional context
> fix(iot-dev): Fix bug where AMQP reactor isn't free'd if closing encounters an exception

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/DesiredPropertiesTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java
Previously, the client only exposed a PATCH API. #719 shows that customers are interested in having a replace API as well.
> feat(iot-service): Add Twin Client API to replace a twin

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix bug where AMQP layer didn't always release network resources (#1136, #1136) 
- Add API to replace a twin (#1139)
old
{
"device": "1.29.2",
"service": "1.27.2",
"deps": "0.11.2",
"securityProvider": "1.4.0",
"tpmEmulator": "1.1.2",
"provisioningDevice": "1.8.7",
"provisioningService": "1.7.2"
}
new
{
"device": "1.29.3",
"service": "1.28.0",
"deps": "0.11.2",
"securityProvider": "1.4.0",
"tpmEmulator": "1.1.2",
"provisioningDevice": "1.8.7",
"provisioningService": "1.7.2"
}
> release(2021-03-04): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- Fix bug where AMQP layer didn't always release network resources (#1147) 
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.29.4/jar
old
```
{
"device": "1.29.3",
"service": "1.28.0",
"deps": "0.11.2",
"securityProvider": "1.4.0",
"tpmEmulator": "1.1.2",
"provisioningDevice": "1.8.7",
"provisioningService": "1.7.2"
}
```
new
```
{
"device": "1.29.4",
"service": "1.28.0",
"deps": "0.11.2",
"securityProvider": "1.4.0",
"tpmEmulator": "1.1.2",
"provisioningDevice": "1.8.7",
"provisioningService": "1.7.2"
}
```
> release(2021-03-12): bump package versions

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/CbsSenderLinkHandler.java
service requires bearer in the type for AAD tokens, not JWT
> refactor(iot-service): Switch from jwt to bearer

- device/iot-device-client/pom.xml
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/fileupload/FileUploadTask.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/fileupload/FileUploadTaskTest.java
- device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSample.java
- device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSimpleSample.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/FileUploadTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ExportImportTests.java
- service/iot-service-client/pom.xml
A lot of client objects changed names since we took this old dependency (4 major version bumps total), so a lot of code had to be rewritten to use this latest version
This is a nice change on it's own, but it is largely driven by some compatibility issues that the old azure storage SDK has was the incoming azure identity library AAD auth changes. Since both master and preview would benefit from this change, this code will be merged into master first, and preview will get it when we merge master into preview shortly thereafter
> refactor(iot-dev): Upgrade azure storage SDK dependency to the latest

- iot-e2e-tests/common/pom.xml
This change unblocks the gate while we work to reduce the number of registry operations done in a typical gated test run.
For additional context if you missed why the gate is blocked, IoT Hub has started responding much slower to registry operations as of late, and the load of registry operations imposed by our tests is pretty high, so a lot of tests would just time out when trying to create a device to run a test on. Re-running these timed out tests after all other tests have finished seems to resolve this issue for us.
> fix(ado): Rerun failed tests up to twice if necessary

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
Same as [this change](https://github.com/Azure/azure-iot-sdk-csharp/commit/666df0e5607fdd9d462cdf4227afc54342bf7dba) in the .NET repo, the device's model Id should be URL encoded before being added to the URI, because it is user-supplied data and could potentially have characters that would break the URI.
> fix(device): encode ModelId during MQTT connect

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/TransportClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceIOTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
A multiplexed connection shouldn't drop just because one of its devices dropped its session, even if that is the only session.
#1187
> fix(iot-dev): Fix bug where amqp layer treated single device multiplexed connections as though they weren't multiplexed

- doc/settings/README.md
- doc/settings/codestyles/Default.xml
- doc/settings/fileTemplates/internal/Class.java
- doc/settings/fileTemplates/internal/Enum.java
- doc/settings/fileTemplates/internal/Interface.java
New installs of Intellij can import these settings in order to get the correct bracing style and file headers. I'll include some documentation around using this in our team's one note
> Add code style and file template settings for Intellij

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- iot-e2e-tests/iot-e2e-jvm-tests/pom.xml
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Moved some AMQP layer code from IoT Hub service client to IoT Hub deps so that it could be shared with IoT Hub device client (#1184)
- Added support for tracking state of outgoing messages (#1190)
- Fix bug where file upload APIs didn't throw an exception if they receive an unsuccessful IoT Hub level status code (#1186)
- Fix regression where MQTT layer did not use new SAS token during reconnection logic. This regression affected device client versions 1.29.2, 1.29.3, and 1.29.4 (#1165)
- Fix bug where MQTT layer did not URL encode modelId when connecting to service (#1168)
- Fix deadlock within MQTT layer when client opens with message callback set and cloud to device message queue is full (#1155)
- Upgrade Azure Storage dependency version (#1158)
- Fix bug where Amqp layer treated …
> release(2021-04-28): bump package versions

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethod.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/RawTwinQuery.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/models/DigitalTwinInvokeCommandRequestOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSend.java
Constructors shouldn't use the (at)returns since they always return the created instance. Several methods were missing (at)params or (at)returns statements as well
> fix some javadocs

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
The expected connection status callbacks were not executed due to this bug. For instance, opening a multiplexed connection with no devices registered wouldn't execute the multiplexing client level connection status callback.
This also fixes a similar bug where the multiplexing client level retry policy isn't used under the same conditions
#1188 for additional context
> fix(iot-dev): Fix bug where transport layer treated multiplexed connections with one or fewer devices as a non-multiplexed connection

- service/iot-service-samples/role-based-authorization-sample/readme.md
- service/iot-service-samples/role-based-authorization-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/RoleBasedAuthenticationSample.java
These links will help users figure out how to setup the service side configurations to do AAD auth.
> doc(iot-service): Add links to new service documentation around role based authentication

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
Draft release notes:
- Add user assigned managed identity support for IoT hub import and export jobs (#1205) 
- Updated reference to com.microsoft.azure.sdk.iot:iot-deps:0.12.0
- Fixed a bug where transport layer treated multiplexed connections with one or fewer devices as a non-multiplexed connection (#1198)
- Fixed a bug where the MultiplexingClient would close the entire multiplexed connection if a single multiplexed device session exhausted its retry attempts (#1202)
- Fixed a bug where DeviceClient would execute the connection status callback for an already disconnected multiplexed device when the user closed the multiplexed connection (#1202)
- Add user assigned managed identity support for IoT hub import and export jobs (#1205)
- Updated reference to …
> release(2021-05-10): bump package versions

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Device.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinDevice.java
Not allowed to do self-enclosing <a> blocks since there would be no link to click on
> doc(iot-service): Fix some javadocs

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/DeviceTwinWithVersionTests.java
deviceTwinWithVersion tests were still creating and removing test identities on their own rather than going through the centralized function that allows for recycling of test identities
The multiplexing test is arguably redundant because we already have a test that you can open a mux connection with the max number of devices. The only difference is registering the devices before vs after open. Since we already have a test that makes sure that registering after open works just like registering before open, there is no need for this test.
> refactor(e2e): Remove redundant multiplexing test, fix deviceTwinWithVersionTest to recycle identities

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
IoT Hub itself does not support twin or method APIs when connecting over HTTP, so the SDK should notify users accordingly
A customer recently tried to use twin APIs over HTTPS and the SDK did not give descriptive errors to signal to the user that the service doesn't support the scenario, so these UnsupportedOperationExceptions will do that instead.
> fix(iot-dev): Make device client throw UnsupportedOperationException for twin/methods when using HTTPS

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
Rather than throw an exception internally when a device gets unregistered during its own reconnection, simply end the reconnection process since the user doesn't want the device on the multiplexed connection anymore anyways
> fix(iot-dev): Make multiplexed connections handle device registrations during reconnection more gracefully

- device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSample.java
- device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSimpleSample.java
Azure blobClient does not work with FileInputStream as it does not support mark/reset. We can either use BufferedFileInputStream or call uploadFromFile. The later is simpler so  I have updated the samples to use that. Now the samples upload files successfully without any exception.
> fix(sample): Fix file upload sample.

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
-Fixed a bug where multiplexing client retry logic for a particular device session did not abandon reconnection when a non-retryable exception is thrown
-Fixed a bug where registering a device to an active multiplexed connection times out if the registration fails due to an issue like if the device is disabled
-Fixed a bug where opening a multiplexing client times out if one or more of the registered devices is disabled. Now the open call will succeed, but the connection status of the disabled device will go DISCONNECTED shortly afterwards. This is a little confusing, but the service itself does open the device session briefly, so it isn't possible for us to fail the open call
> fix(iot-dev): Fix a few small multiplexing bugs

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Added support for Twin metadata properties, applicable when using configuration (#1219)
- DeviceClient/ModuleClient now throws an UnsupportedOperationException when using twin/method APIs over HTTP rather than failing with service error (#1204)
- Fixed a bug where multiplexed connections couldn't handle device registrations during reconnection (#1209)
- Fixed a bug where multiplexing client retry logic did not abandon reconnection when a non-retryable exception is thrown (#1218)
- Fixed a bug where registering a device to an active multiplexed connection times out if the registration fails due to an issue like if the device is disabled (#1218)
- Fixed a bug where opening a multiplexing client times out if one or more of the registered devices is disabled. Now the open call will succeed, …
> release(2021-05-24): bump package versions

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/RegistryManagerTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManagerOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethod.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethodClientOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinClientOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinClientOptions.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobClientOptions.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/RegistryManagerTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethodTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinTest.java
- service/iot-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/service/jobs/JobClientTest.java
Rather than set the default values for these fields in the constructor that builds these options objects, just set them in the options objects directly
> refactor(iot-service): Set default values in option objects

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TransportClientTests.java
TransportClient tests have failed occasionally with timeout errors around this scenario. The scenario seems fine, but higher loads on a hub at the time may take the service longer to ack the method subscription, so increasing this timeout should help
> refactor(e2e): make method subscribe timeout longer

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
When registering X devices to an open connection and 1 of them is disabled, the register call will throw a MultiplexingClientDeviceRegistrationAuthenticationException, but X-1 devices successfully added their session to the active multiplexed connection. This needed to be clarified since the javadocs didn't call this out.
There are two bug fixes here. The first bug fix is simply that the transport layer forgot to remove the device from the set of registered devices if it failed to register in a scenario like the above. It was never successfully registered, so the transport layer should have the same state. 
The second bug is that the MultiplexingClient layer should update it's state accordingly in these partial success scenarios as well. Previously, if it threw an exception in a scenario …
> fix(iot-dev): clarify/fix how partial successes work for MultiplexingClient bulk registrations

- deps/pom.xml
- provisioning/security/x509-provider/pom.xml
Customers are hitting this issue from our bouncycastle dependencies: https://github.com/bcgit/bc-java/issues/661
The resolution is simply to upgrade the bouncycastle dependency to at least 1.65
> refactor(deps, x509-provider): Bump bouncycastle versions to 1.65

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Increase dependency versions for bouncycastle to 1.65 (#1232)
- Increase dependency versions for bouncycastle to 1.65 (#1232)
- Fixed a bug partially successful bulk registrations of devices to multiplexed connections didn't update local state properly (#1231)
- Increase dependency versions for bouncycastle to 1.65 (#1232)
- Increase dependency versions for bouncycastle to 1.65 (#1232)
- Increase dependency versions for bouncycastle to 1.65 (#1232)
- Increase dependency versions for bouncycastle to 1.65 (#1232)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.30.3/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/1.31.1/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-deps/0.13.1/jar …
> release(2021-06-07): bump package versions

- provisioning/provisioning-samples/provisioning-symmetrickey-group-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ComputeDerivedSymmetricKeySample.java
- provisioning/provisioning-samples/provisioning-symmetrickey-group-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningSymmetricKeyEnrollmentGroupSample.java
We need to separate the derivation of the device-specific symmetric key to a different sample as per the service team's recommendation. Users shouldn't save the enrollment group level key to each device, and that's what our sample showed previously
> refactor(samples): Refactor symmetric key enrollment group samples to show best practices

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
These options can drastically alter how the SDK behaves, so for future debugging purposes, they should be logged when set
> refactor(iot-dev): Add log statements for setOption methods

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- readme.md
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
This release is an LTS release. See here for more details on what this means:
https://github.com/Azure/azure-iot-sdk-java#long-term-support
- Increase dependency versions for bouncycastle to 1.69 (#1245)
- Add new Digicert Global Root G2 certificate to trusted root chain (#1247)
- Increase dependency versions for bouncycastle to 1.69 (#1245)
- Add new Digicert Global Root G2 certificate to trusted root chain (#1247)
- Increase dependency versions for bouncycastle to 1.69 (#1245)
- Add new Digicert Global Root G2 certificate to trusted root chain (#1247)
- Fixed a bug where subsequent calls to receive file upload notifications and feedback messages failed (#1238)
- Increase dependency versions for bouncycastle to 1.69 (#1245)
- Add new Digicert Global Root G2 certificate to trusted root …
> Release 2021 06 17

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
This log was executing even for x509 connections that have no authentication links to wait for
> refactor(iot-dev): Fix an AMQP log statement

- device/iot-device-samples/device-reconnection-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceClientManager.java
~~The previous implementation did not try to open the connection again if a call to open() threw an exception. This new implementation will retry the open call if that happens.~~
So the only actual issue here is that the doConnect method appeared to not have retry baked in, but it actually did. I'd like to rename the method accordingly so that others don't make the same mistaken assumption that I made
> fix(sample): Fix issue in device reconnection sample

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/TransportClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceIOTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/InternalClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/TransportClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/telemetry/SendMessagesTests.java
This adds an optional parameter to the open calls for device, module, and multiplexing client that allows for users to opt in to get retry on their open call.
> feat(iot-dev): Add support for opening clients with retry

- provisioning/provisioning-samples/service-bulkoperation-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceBulkOperationSample.java
- provisioning/provisioning-samples/service-enrollment-group-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceEnrollmentGroupSample.java
- provisioning/provisioning-samples/service-enrollment-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceEnrollmentSample.java
- provisioning/provisioning-samples/service-update-enrollment-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceUpdateEnrollmentSample.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/ProvisioningServiceClient.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroup.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollment.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/X509Attestation.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/X509CAReferences.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/X509Certificates.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/ProvisioningServiceClientTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/BulkEnrollmentOperationTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollmentTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/X509AttestationTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/X509CAReferencesTest.java
- provisioning/provisioning-service-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/provisioning/service/configs/X509CertificatesTest.java
For the provisioning service client, unlike other service clients, we didn't have any deprecated constructors/factory methods. However, to maintain parity with the service clients in the IoT hub packages that have constructors rather than factory methods, I'm proposing:
current
```java
public static ProvisioningServiceClient createFromConnectionString(String connectionString);
// note that this is currently private
private ProvisioningServiceClient(String connectionString)
```
proposed:
```java
//not deleted since it wasn't deprecated
public static ProvisioningServiceClient createFromConnectionString(String connectionString);
//private -> public
public ProvisioningServiceClient(String connectionString)
```
This change would only be additive, not breaking
> break(dps-service): Remove deprecated APIs from DPS service package and samples

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClientOptions.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
Also fix a bug where setting the send and/or receive period after opening the client didn't change the period.
For additional context here, the Java SDK has a periodic thread that checks for queued messages to send, and that thread currently only sends 10 messages at most, even if more messages are queued. This feature allows users to configure this value instead of leaving it hardcoded.
> feat(iot-dev): Add ability to configure the maximum number of messages sent per send thread

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
Clients using MQTT were limited to 10 messages in flight at a time, which hurt the client's ability to achieve higher messaging throughputs. Raising this value to a higher number. We can make this value configurable at some point in the future if someone asks for it, but this value should be enough to not hamstring anyone.
"In-flight" messages are messages that have been sent, but haven't been ack'd yet.
> refactor(iot-dev): Raise the max in flight messages limit for mqtt

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- Fixed bug where multiplexed deviceClients did not maintain twin and/or method subscriptions after reconnection (#1298)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.32.1/jar
old
{
"device": "1.32.0",
"service": "1.33.0",
"deps": "0.15.0",
"tpmEmulator": "1.1.2",
"provisioningDevice": "1.10.0",
"provisioningService": "1.9.0"
}
new
{
"device": "1.32.1",
"service": "1.33.0",
"deps": "0.15.0",
"tpmEmulator": "1.1.2",
"provisioningDevice": "1.10.0",
"provisioningService": "1.9.0"
}
> release(2021-08-09): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientType.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClientType.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/FileUpload.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ReportedPropertiesParameters.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/DeviceIOTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/InternalClientTest.java
- device/iot-device-client/src/test/java/tests/unit/com/microsoft/azure/sdk/iot/device/ModuleClientTest.java
Move all the common code into InternalClient as well. There are many changed sample/test files that are affected by these renames, but for the sake of simplifying this PR, those changes will be added later.
old:
```java
public void subscribeToDesiredProperties(...);
public void startTwin(...);
public void getTwin(...);
public void subscribeToDeviceMethod(...); //deviceClient
public void subscribeToMethod(...); //moduleClient
public void registerConnectionStatusChangeCallback(...);
```
new
```java
public void subscribeToDesiredPropertiesAsync(...);
public void startTwinAsync(...);
public void getTwinAsync(...);
public void subscribeToMethodsAsync(...); //moduleClient and deviceClient, "Methods" rather than "Method"
public void setConnectionStatusChangeCallback(...); //"set" instead of …
```
> break(iot-dev): Rename device/module client APIs for consistency

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
These identities could have been recycled into other tests where the twin state is important, so need to mark them accordingly
> fix(e2e): fix multiplexing tests not setting test identity's twinUpdated to true

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethod.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/RawTwinQuery.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobClient.java
The ```synchronized``` keyword on a method simply means that a given instance of the class that contains that method cannot invoke the method or any other synchronized method at the same time. It makes them behave like atomic operations.
A given device method client should be allowed to invoke a method on device "a" while already invoking a method on device "b". The service will protect users from trying to invoke multiple methods on the same device simultaneously.
These APIs do not share any local resources that we needed to synchronize on. They are just simple HTTP requests to the service that are constructed locally within the method call itself.
> break(iot-serv, iot-dev): Remove unnecessary synchronization from public methods

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/ProvisioningDeviceClientRegistrationResult.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/ProvisioningDeviceClientSubstatus.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/exceptions/ProvisioningDeviceHubException.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/parser/DeviceRegistrationResultParser.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/ProvisioningTask.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RegistrationResult.java
The service has sent these fields for a while, but we never exposed them to users for some reason. This brings our registration result class up to par with what the service sends to the SDK
> feat(dps-dev): Add missing registration result fields

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
This is a special preview release for our upcoming 2.0.0 clients. There are substantial changes made to the SDK in this upcoming version, and the brief summary of them can be seen below:
- Trusted certificates are read from the physical device's trusted root certification authorities certificate store rather than from source.
- Removed all deprecated APIs 
- Removed unthrown exceptions from declared exceptions list for all APIs
- Removed support for parsing certificates
- Trusted certificates are read from the physical device's trusted root certification authorities certificate store rather than from source.
- Removed all deprecated APIs 
- Removed support for parsing certificates
- Renamed several APIs for consistency between Module and Device clients
- Removed unthrown exceptions from …
> release(2021-08-30): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsBatchMessage.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsIotHubConnection.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/https/HttpsBatchMessageTest.java
StringBuilder is much more efficient than just concatenating strings directly
> fix(iot-dev): Fix inefficient way of building strings in https batch messages

- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroup.java
- provisioning/provisioning-service-client/src/test/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java
This check was not compatible with getting chained certificates
#1340
> fix(prov-serv): Remove SDK side validation for x509 Attestation object format when parsing enrollmentGroups

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
- service/iot-service-client/src/test/java/com/microsoft/azure/sdk/iot/service/ServiceClientTest.java
Previously, async operations may have continued from the service client even after closing it
> fix(iot-serv): Fix bug where service client's thread pool wasn't shutdown when the service client is shutdown

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
There are no usages of these methods in our e2e tests that we need to update. They do still have some unit tests, though
> refactor(iot-serv): deprecate async service client and registry manager APIs

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
If close is called during reconnection, it will block until the current reconnection attempt completes (successfully or not) before closing the connection and marking the local state as closed
If reconnection is initiated during a close, it will block until the close call has finished tearing down the connection and marking the local state as closed. After the close call has finished, the reconnection logic will immediately give up since the client was closed
#1343
> fix(iot-dev): Fix race condition where reconnection logic could carry on after client was closed

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix inefficient way of building strings in https batch messages (#1335)
- Fix bug where multiplexed client had more session handlers than expected (#1341)
- Fix exception message in mqtt layer (#1351)
- Fix how the client handles failed disconnections (#1338) 
- Fix connection status reporting CONNECTED before all SDK states are CONNECTED (#1355)
- Fix race condition where reconnection logic could carry on after client was closed (#1356
- Correct verbosity of correlation warnings and fix the callback context map (#1357)
- Remove SDK-side validation of symmetric key format (#1324)
- Add missing provisioning registration result fields (#1313)
- Remove SDK side validation for x509 Attestation object format when parsing enrollmentGroups (#1342) …
> release(2021-09-15): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix inefficient way of building strings in https batch messages (#1335)
- Fix bug where multiplexed client had more session handlers than expected (#1341)
- Fix exception message in mqtt layer (#1351)
- Fix how the client handles failed disconnections (#1338) 
- Fix connection status reporting CONNECTED before all SDK states are CONNECTED (#1355)
- Fix race condition where reconnection logic could carry on after client was closed (#1356
- Correct verbosity of correlation warnings and fix the callback context map (#1357)
- Remove Service Client async APIs
- Remove SDK-side validation of symmetric key format (#1324)
- Add missing provisioning registration result fields (#1313)
- Remove SDK side validation for x509 Attestation object format when parsing enrollmentGroups (#1342) …
> release(2021-09-16): bump preview package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
A few customers have been confused about this point, so it is worth adding some clarification around it.
> doc(iot-dev): Add additional documentation to connection status callback

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- feat(iot-dev): Add support for Plug and Play feature over AMQP, add componentName as optional field for telemetry (#1371)
- Remove client side validation of x509 CA references format (#1367)
old
{
"device": "1.32.3",
"service": "1.33.1",
"deps": "0.15.0",
"provisioningDevice": "1.11.0",
"provisioningService": "1.9.1"
}
new
{
"device": "1.33.0",
"service": "1.33.1",
"deps": "0.15.0",
"provisioningDevice": "1.11.0",
"provisioningService": "1.9.2"
}
> release(2021-10-05): bump package versions

- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/amqp/AmqpsConnection.java
- deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClientConfig.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubReceiveTask.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubSendTask.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/ReactorRunner.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/ProvisioningDeviceClientConfig.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/ProvisioningDeviceClientContract.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/amqp/ContractAPIAmqp.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/amqp/ProvisioningAmqpOperations.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/http/ContractAPIHttp.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqtt.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/ProvisioningTask.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RegisterTask.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/StatusTask.java
- provisioning/provisioning-device-client/src/test/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/StatusTaskTest.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpConnectionHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpFileUploadNotificationReceive.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpReceive.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpSend.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/ReactorRunner.java
> (feat): Make thread names identifiable.

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
How the amqp session handles a given twin/method subscription message wasn't logged, which could lead to some ambiguity
> refactor(iot-dev): Add additional logging to amqp layer

- device/iot-device-samples/device-reconnection-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceClientManagerSample.java
This sample uses environmental variables while all the other samples uses command line arguments. Changing this sample to use command line arguments for consistency.
Reimplement setup logic for using either environmental variables or command line arguments to setup the sample run.
> standardize on command-line arguments and environment variable

- .github/workflows/github_issues.yml
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenAuthenticationProvider.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenProvidedAuthenticationProvider.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportTest.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/TokenRenewalTests.java
The reason was always "NO_NETWORK" because the exception was retriable. It makes more sense to first check if the SAS token is expired, and then to check if it is retriable
#1405
> fix(iot-dev): Fix bug where routine MQTT SAS token expired disconnects didn't provide the correct reason

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubReceiveTask.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubSendTask.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/DeviceIOTest.java
As a result, there would be lingering threads that would build up over time.
#1412
> fix(iot-dev): fix bug where reconnection events wouldn't fully close the send/receive thread pools before creating new thread pools

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java
The services we use to run these tests are currently offline, so the tests should be disabled
> fix(e2e): Disable invalid server cert validation tests

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/ProvisioningDeviceClient.java
- provisioning/provisioning-service-client/pom.xml
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/ProvisioningServiceClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/RegistryManager.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/ServiceClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceMethod.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/digitaltwin/DigitalTwinAsyncClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobClient.java
Making the SDK log this should help us deal with any confusion we get from customer logs where the user claims to use one version of the SDK but the logs don't appear to come from that version
> refactor(iot-dev, iot-serv, dps-dev, dps-serv): Add logs to clients that say what version is being run

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
The worker thread would still be woken up by a newly queued message. It just wouldn't be woken up if the only newly queued message was a message being retried.
> fix(iot-dev): Fix bug where a retry scheduled message wouldn't wake up worker thread

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Make thread names more identifiable (#1395)
- Make thread names more identifiable (#1395)
- Added additional logging to amqp layer (#1406, #1435)
- Add support for configuring keep-alive interval for amqps and mqtt (#1408)
- Add logs to client that says what version is being run (#1430)
- Fix potential deadlock when closing while reconnecting (#1393)
- Fix bug where routine MQTT SAS token expired disconnects didn't provide the correct reason (#1407)
- Fix bug where reconnection events wouldn't fully close the send/receive thread pools before creating new thread pools (#1413)
- Fix bug where a retry scheduled message wouldn't wake up worker thread (#1439)
- Fix amqp message acknowledgements being sent from outside the reactor thread which may cause a race condition (#1442)
- Add missing …
> release(2021-12-15): bump package versions

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ServiceClientTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/AmqpConnectionHandler.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/amqps/ReactorRunner.java
Service allows up to 65 kb so this fix brings the SDK in line with the service's advertised limits
#1420
> fix(iot-serv): Fix service client limiting amqps_ws messages to 16 kb

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
When the IoT Hub client times out for a keep alive, usually it will send a close packet which will be acknowledged by the client and gracefully shut down the connection. In some cases if the TCP socket is unresponsive but not yet closed it will cause the Close packet to be lost and the client will hang indefinitely.
This change allows for us to check to see if the connection has been closed by proton-j and call our local close methods to allow the client and customer to react to this situation.
> fix (client): Add ability to locally close connection on timeout

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClientConfig.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/InternalClientTest.java
When using a security provider the keep alive defined in the ClientOptions is not set.
> fix(client): Honor keepalive when using security provider

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
Lower log level of some statements from INFO to DEBUG to make the execution details less verbose.
Our customer submits a [feature request](https://github.com/Azure/azure-iot-sdk-java/issues/1457) regarding less-verbose log statements for execution details. 
Lower log level for the statements that are less important to users.
> Update Logging level in device.transport.IotHubTransport

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceMethod.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDeviceMethodTest.java
method response messages should always be sent. Tracking them like this only allowed issues like #1465 to happen if the state is lost somehow
This state is already not tracked for methods in AMQP
> fix(iot-dev): Remove unnecessary tracking of direct method request Ids

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- Reduced log levels of some frequent log statements to avoid flooding logs (#1459)
- Removed unnecessary tracking of direct method request Ids that resulted in unnecessary errors logged like #1465 (#1468)
- Fix bug where deviceClient did not honor keep alive settings if constructed using security provider (#1455)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.34.2/jar
old
{
"device": "1.34.1",
"service": "1.34.1",
"deps": "0.15.2",
"provisioningDevice": "1.11.1",
"provisioningService": "1.9.3"
}
new
{
"device": "1.34.2",
"service": "1.34.1",
"deps": "0.15.2",
"provisioningDevice": "1.11.1",
"provisioningService": "1.9.3"
}
> release(2022-02-18): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Upgrade bouncycastle dependency versions to 1.70 (#1476)
- Upgrade gson dependency version to 2.8.9 (#1476)
- Upgrade jackson-databind dependency version to 2.11.3 (#1476)
- Upgrade iot-deps package dependency to 0.15.3 (#1476)
- Upgrade iot-deps package dependency to 0.15.3 (#1476)
- Upgrade iot-deps package dependency to 0.15.3 (#1476)
- Upgrade iot-deps package dependency to 0.15.3 (#1476)
- Upgrade com.microsoft.rest:client-runtime dependency to 1.7.14 (#1476)
- Upgrade bouncycastle dependency versions to 1.70 (#1476)
old
{
"device": "1.34.2",
"service": "1.34.1",
"deps": "0.15.2",
"provisioningDevice": "1.11.1",
"provisioningService": "1.9.3"
}
new
{
"device": "1.34.3",
"service": "1.34.2",
"deps": "0.15.3", …
> release(2022-03-04): bump package versions

- vsts/generate_javadocs_branch.ps1
Removes references to deps folder which was removed in a recent update.
> Remove references to deps in Javadoc pipeline script

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsReceiverLinkHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSasTokenRenewalHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSenderLinkHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
The proton-j reactor powering the multiplexed connection still had references to the various amqp handler objects used in our SDK even after the client using each of these handlers had been unregistered. By clearing the handlers from the reactor, the JVM is free to garbage collect these handlers
Also fix a few small state maps that weren't kept up to date whenever a client was unregistered from a muxed connection
#1478
> fix(iot-dev): Fix issue where multiplexed connections would leak heap memory for unregistered device clients

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/MessagingClientTests.java
Basic tier hubs do not support cloud to device telemetry, so we can't test it.
The other c2d tests were already marked this way, but this test was not. This test was failing in CI builds of basic tier hubs. The only reason this hasn't been a problem yet is that this test was skipped in PR builds.
> refactor(e2e): Mark a c2d test as standard tier only

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsReceiverLinkHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSasTokenRenewalHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSenderLinkHandler.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
#1478
The reactor instance still held onto the last scheduled SAS token renewal task for an unregistered device when it needed to be cancelled, and the sessions and links needed to be free'd after they were closed.
> fix(iot-dev): Fix SDK leaking apache qpid objects after unregistering a device

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/ConfigurationsClientTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/configurations/ConfigurationContent.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/configurations/ConfigurationsClient.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/configurations/serializers/ConfigurationContentParser.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/configurations/serializers/ConfigurationParser.java
- service/iot-service-client/src/test/java/com/microsoft/azure/sdk/iot/service/configurations/ConfigurationContentParserTest.java
- service/iot-service-client/src/test/java/com/microsoft/azure/sdk/iot/service/configurations/ConfigurationsClientTest.java
It always sent empty json objects for ModuleContent, ModulesContent, and DeviceContent even if the user provided one or more key-value pairs for it
Also fix a bug where numeric configuration values were always serialized and deserialized as floats even if they were integers
> fix(iot-dev): Fix bug where configuration content was not serialized correctly

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/TwinClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/TwinTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/Twin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/TwinCollection.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/TwinProperties.java
Example twin:
```
{
"deviceId": "devA",
"etag": "AAAAAAAAAAc=", 
"status": "enabled",
"statusReason": "provisioned",
"statusUpdateTime": "0001-01-01T00:00:00",
"connectionState": "connected",
"lastActivityTime": "2015-02-30T16:24:48.789Z",
"cloudToDeviceMessageCount": 0, 
"authenticationType": "sas",
"x509Thumbprint": {     
"primaryThumbprint": null, 
"secondaryThumbprint": null 
}, 
"version": 2, 
"tags": {
"$etag": "123",
"deploymentLocation": {
"building": "43",
"floor": "1"
}
},
"properties": {
"desired": {
"telemetryConfig": {
"sendFrequency": "5m"
},
"$metadata" : {...}, // <----- was missing
"$version": 1
},
"reported": {
"telemetryConfig": {
"sendFrequency": "5m",
"status": "success"
},
"batteryLevel": 55,
"$metadata" : {...}, // <----- was missing
"$version": 4
}
}
}
```
> fix(iot-service): Fix bug where twin metadata isn't given to user even when it was received from service

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix bug where synchronous operations did not throw an exception if it received an unsuccessful status code (#1512)
- Fix bug where AMQP connections did not map AmqpLinkMessageSizeExceededException to REQUEST_ENTITY_TOO_LARGE (#1512)
- Fix stack traces for synchronous methods not including the synchronous method call itself (#1512)
- Fix bug where multiplexing client did not cancel queued or sent packets for a device when it is unregistered (#1503)
- Fix a bug where numeric configuration values were always serialized and deserialized as floats even if they were integers (#1510)
- Fix bug where configuration content was not serialized correctly (#1510)
- Fix bug where SDK rejected deserialized registry device instances with no authentication details (#1508)
- Fix bug where twin metadata …
> release(2022-04-06): bump package versions

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
Some of these tests involve creating and testing hundreds of devices so the usual test timeout is too restrictive
> refactor(e2e): Increase test timeout for multiplexing client e2e tests

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
also fix an e2e test not getting the initial twin before sending reported property updates
> fix(iot-dev): Fix bug where multiplexed devices didn't persist subscriptions if transport error occurred

- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
Continuing on #1522 but adding the same logic in the other build steps
> ado: Make component governance run on android build and test

- device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java
- device/iot-device-samples/module-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ModuleTwinSample.java
Previous implementation failed with "precondition failed" error because it wasn't using the reported properties version correctly
Converting the async twin API uses into sync API uses since we were just blocking on them anyways. Also adding a lot more comments explaining how to keep the versions of your reported properties up to date and what to do when they are out of date and your request fails with "precondition failed"
The module and device samples here are identical, so the same changes have been made to both
> refactor(sample): Refactor device twin sample

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
As a result, this call would fail:
```java
deviceClient.open();
deviceClient.subscribeToMethods(...);
deviceClient.close();
deviceClient.open();
deviceClient.subscribeToMethods(...); // would always timeout since the callbacks pointed at the previous client's method state
```
> fix(iot-dev): Fix bug where twin/method subscription wasn't cleared when client is closed

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Remove accidentally added dependency on a logging binding library (#1524)
- Fix bug where twin/method subscription wasn't cleared when client is closed (#1536)
- Fix IO errors and time outs not being classified as retryable (#1534)
- Fix bug where multiplexed devices didn't persist subscriptions if transport error occurred (#1525)
- Upgrade Guava and Jackson dependencies (#1529)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/2.0.2/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/2.0.2/jar
old
{
"device": "2.0.1",
"service": "2.0.1",
"securityProvider": "2.0.0",
"tpmHsm": "2.0.0",
"x509": "2.0.0",
"provisioningDevice": "2.0.0",
"provisioningService": "2.0.0"
}
new
{
"device": "2.0.2",
"service": "2.0.2", …
> release(2022-04-18): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/methods/DirectMethodsTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/TwinTests.java
Subsequent calls would overwrite some callbacks but not all callbacks. This makes each call overwrite all the callbacks instead.
```java
deviceClient.open(false);
deviceClient.subscribeToMethods(...); // succeeds
deviceClient.subscribeToMethods(...); // times out, sends notifications to callbacks registered in the previous call
```java
> fix(iot-dev): fix bug where subsequent calls to subscribe to twin/methods times out

- provisioning/security/x509-provider/pom.xml
Hi! I found the pom file of project **_com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:2.0.0_** introduced **_6_** dependencies. However, among them, **_1_** libraries (**_16%_**) are not used by your project. I list the redundant dependencies below (labelled as red ones in the figure):
commons-codec:commons-codec:jar:1.14:compile
---
Removing the redundant dependencies can reduce the size of project and prevent potential dependency conflict issues (i.e., multiple versions of the same library). More importantly, one of the redundant dependencies **_commons-codec:commons-codec:jar:1.14:compile_** induced dependency conflict in the dependency graph. As such, I suggest a refactoring operation for **_com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:2.0.0_**’s …
> Could com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:2.0.0 drop off redundant dependencies? 

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
- device/iot-device-samples/android-sample/app/build.gradle
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
- pom.xml
- Fixed bug where subsequent calls to subscribe to twin/methods times out (#1545)
- Handle an issue with proton-j reactor's internal state during cleanup (#1542)
- Remove unnecessary creation of custom symbol instances in amqp layer (#1541)
- Removed unused apache commons-codec dependency (#1543) 
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/2.0.3/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning.security:x509-provider/2.01/jar
before
{
"device": "2.0.2",
"service": "2.0.2",
"securityProvider": "2.0.0",
"tpmHsm": "2.0.0",
"x509": "2.0.0",
"provisioningDevice": "2.0.0",
"provisioningService": "2.0.0"
}
after
{
"device": "2.0.3",
"service": "2.0.2",
"securityProvider": "2.0.0",
"tpmHsm": "2.0.0",
"x509": "2.0.1", …
> release(2022-05-03): bump package versions

- pom.xml
Not exactly for Gson-related [dependabot alerts](https://github.com/Azure/azure-iot-sdk-java/security/dependabot) here, as we are using patched version 2.8.9 already. The security alerts were triggered as dependabot could not determine the currently installed version.
> refactor(all): update Gson dependency in main pom

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/telemetry/SendMessagesTests.java
- supported_platforms.md
- vsts/build_repo.ps1
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
[Java releases for reference](https://whichjdk.com/#releases)
The majority of our non-android users use Java 11 currently, so this PR adds PR and nightly testing of Java 11 to our gates. This PR also relegates Java 8 testing to nightly only in order to save time at the gate.
> Add Java 11 testing

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/QueryClientTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/Twin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/TwinState.java
Added getter/setter for missing Twin fields reported by customer (reported using Ava: 2206170060000042)
Following are the fields: status, statusUpdateTime,. connectionState, LastActivityTime, cloudToDeviceMessageCount.
Also updated unit test::  testQueryTwins() to validate the fields.
> Added getter/setter for missing Twin fields

- device/iot-device-client/pom.xml
- iot-e2e-tests/common/pom.xml
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientComponentTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/digitaltwin/DigitalTwinClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningServiceClientTests.java
- iot-e2e-tests/iot-e2e-jvm-tests/pom.xml
- iot-e2e-tests/iot-e2e-jvm-tests/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/TokenCredentialTests.java
- provisioning/provisioning-device-client/pom.xml
- provisioning/provisioning-service-client/pom.xml
- provisioning/security/pom.xml
- service/iot-service-client/pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/Twin.java
- vsts/build_e2e_tests.cmd
- vsts/build_repo.ps1
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
-DskipTests skipped both the unit tests and the e2e tests, but we only want to skip e2e tests at this step.
Also tag a few e2e test classes that were missing tags
> Fix unit tests not being run at the gate

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/QueryClientTests.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/Twin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/TwinState.java
> Getter setter for twin fields

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
For #1563:
Before this fix, the reconnect thread was not cleared appropriately. As a result, an instance of `IotHubReconnectTask` would be created per connection-status change from "DISCONNECTED_RETRYING" to "CONNECTED", while the previous thread was still waiting until the connection turned into "DISCONNECTED" eventually. 
Thread dump **before** this fix:
Thread dump **after** this fix:
> fix(iot-dev): fix thread-leak issue with IotHubReconnectTask

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
+ Upgrade Gson dependency version to 2.9.0 (#1557)
+ Fix thread-leak issue with IotHubReconnectTask (#1567)
+ Upgrade Gson dependency version to 2.9.0 (#1557)
+ Add missing fields with getters and setters to Twin and TwinState classes(#1562)(#1566)
+ Upgrade Gson dependency version to 2.9.0 (#1557)
+ Upgrade Gson dependency version to 2.9.0 (#1557)
> release(2022-07-07): bump package versions

- vsts/echo_versions.ps1
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
JDK version is set later in the pipeline, but it would be nice to set here as well so we can get the JDK 11 version instead of whatever default JDK version the build agent has set.
> Fix build pipeline only echoing JDK 8 version

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSessionHandler.java
DeviceClient doesn't fully reconnect after temporary network disconnect (AMQP), attempts to invoke direct method fails.
Removed unnecessary boolean which were intended to carry over state between reconnection.
With each reconnection, we instantiate new SessionHandler but only set the boolean to true (and create method/twin links) when sending first message during initial connection, thus during reconnection we never create method/twin links.
github issue: https://github.com/Azure/azure-iot-sdk-java/issues/1571
> fix(iot-device): fix issue with direct method after reconnect from temporary network disconnect - AMQP

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/QueryClientTests.java
- pom.xml
+ Fixed bug where direct method fails after reconnecting from temporary network disconnect [(#1577)](https://github.com/Azure/azure-iot-sdk-java/pull/1577)
> release(2022-07-25): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/twin/DirectMethodResponse.java
`DirectMethodResponse` takes the property "payload" in `Object` type, but I missed the setter method before.
Found by customer in #1584
> fix(iot-device): change payload type in payload setter from String to Object

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/serviceclient/QueryClientTests.java
The start and end time fields may not be present in the service's response if the job has not finished and/or has not started
> refactor(e2e): Remove some flakey checks in a query test

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/serializers/ScheduledJobParser.java
- service/iot-service-client/src/test/java/com/microsoft/azure/sdk/iot/service/jobs/scheduled/ScheduledJobParserTest.java
The ScheduledJobsClient class improperly sets maxExecutionTimeInSeconds due to a bug in the ScheduledJobParser class
fix create job maxExecutionTimeInSeconds improper json serialization
Github Issue (fix#1591)
- [ X] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/main/.github/CONTRIBUTING.md).
- [ X] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ X] This pull-request is submitted against the `main` branch. 
https://github.com/Azure/azure-iot-sdk-java/issues/1591
The ScheduledJobsClient.scheduleDirectMethod() method and other similar methods ignore the maxExecutionTimeInSeconds as the ScheduledJobParser.java class improperly …
> fix(iot-service): maxExecutionTimeInSeconds improper serialization

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Allow users to set direct method response payload as any object instead of just as a string (#1586)
- Fixed a bug where the maxExecutionTimeInSeconds property was not sent to the service correctly and causing the service to ignore it (#1592)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/2.1.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/2.1.1/jar
old
{
"device": "2.0.5",
"service": "2.1.0",
}
new
{
"device": "2.1.0",
"service": "2.1.1",
}
> release(2022-08-25): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Increase dependency version for Paho (#1595)
- Increase dependency version for Proton-j (#1595)
- Increase dependency version for Proton-j-extensions (#1595)
- Fixed bug where opening AMQP configured DeviceClient with no network connection leaked a file descriptor (#1595)
- Increase dependency version for Paho (#1595)
- Increase dependency version for Proton-j (#1595)
- Increase dependency version for Proton-j-extensions (#1595)
- Increase dependency version for Paho (#1595)
- Increase dependency version for Proton-j (#1595)
- Increase dependency version for Proton-j-extensions (#1595)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/2.1.1/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/2.1.2/jar …
> release(2022-09-13): bump package versions

- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix the authenticationType enum serialization keys (#1600)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/2.1.3/jar
> release(2022-09-28): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportMessage.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDirectMethod.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessaging.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttTwin.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttDirectMethodTest.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnectionTest.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttMessagingTest.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttTest.java
- device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttTwinTest.java
The SDK wasn't checking if the received MQTT messages had QoS of 0 or 1 and attempted to ack all of them because of that.
Received twin/direct method messages are QoS 0 so we will now skip sending ack's for them. 
The previous behavior did cause some bugs when using gwv2 because the received twin/direct method messages could have a messageId of 0. When we tried to ack that message Id, [Paho would override that messageId](https://github.com/eclipse/paho.mqtt.java/blob/f4e0db802a4433645ef011e711646a09ec9fae89/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/ClientState.java#L499) (because it assumed that "messageId == 0" meant that it wasn't assigned a messageId yet) and send an ack for a message that the service never sent. GWv1 seems to handle this bug …
> fix(iot-dev): Fix MQTT layer acknowledgement logic

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/TransportUtils.java
- device/iot-device-samples/android-sample/app/build.gradle
- pom.xml
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/transport/TransportUtils.java
- Fix bug where the client sent PUBACK messages even when the service sent messages with QoS of 0
- Note that this issue caused the bug documented in issue #1590 on some instances of IoT hub, but not all
- Upgrade Jackson dependency
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/2.1.2/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/2.1.4/jar
> release(2022-10-13): bump package versions

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java
- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
twin and methods subscriptions are preserved only through retry whereas c2d callback is preserved even when the client is closed.
> doc(iot-dev): Add notes in javadocs about when subscriptions are preserved

- device/iot-device-client/pom.xml
- provisioning/provisioning-device-client/pom.xml
- provisioning/provisioning-service-client/pom.xml
- provisioning/provisioning-tools/provisioning-x509-cert-generator/pom.xml
- provisioning/security/dice-provider-emulator/pom.xml
- provisioning/security/dice-provider/pom.xml
- provisioning/security/security-provider/pom.xml
- provisioning/security/tpm-provider-emulator/pom.xml
- provisioning/security/tpm-provider/pom.xml
- provisioning/security/x509-provider/pom.xml
- service/iot-service-client/pom.xml
- [✓] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/main/.github/CONTRIBUTING.md).
- [*] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [✓] This pull-request is submitted against the `main` branch. 
I am building Modular Java 18 apps. When I add one or more of these libraries, it breaks my build because the library does not have a module that I can import. 
By adding the Automatic-Module-Name to the jar Manifest, people writing modular Java will still be able to use the libraries without preventing those still on Java 8 from using them.  I have made [this change in other Azure …
> Added Automatic-Module-Name to jar manifests for Modular Java 

- provisioning/provisioning-samples/provisioning-tpm-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningTpmSample.java
Remove some unnecessary class definitions, streamline an async message send call, and use proper wait/notify pattern instead of Thread.Sleep() to wait for provisioning to finish.
> Rework DPS TPM sample

- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/Twin.java
- service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/twin/TwinState.java
- service/iot-service-client/src/test/java/com/microsoft/azure/sdk/iot/service/twin/TwinTest.java
There were some missing null checks and some unnecessary argument-not-null assertions in our twin parsing logic that breaks the ability to query twins with fields filtered down to just one or two fields.
#1611
> fix(iot-serv): Fix serialization of incomplete twin objects

- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/ProvisioningTask.java
- provisioning/provisioning-device-client/src/test/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/ProvisioningTaskTest.java
If the provisioning ended with status DISABLED or FAILED, the SDK previously attempted to to assign a null Integer value (registrationOperationStatusParser.getRegistrationState().getErrorCode()) to the primitive int type used by dpsHubException.setErrorCode(...)
Assigning a null Integer value to the primitive int type caused the ProvisioningTask thread to throw an NPE. As a result, the provisioning state machine stayed locked in ASSIGNING perpetually even though the SDK received the terminal DISABLED/FAILED state from the service.
Co-authored by @sokolowski-daniel 
Thanks to #1640 for pointing out this bug and for providing the fix
> fix(prov-dev): Fix bug in failed and disabled statuses during device provisioning

- pom.xml
- vsts/release/package-maven-artifacts-for-release.ps1
netty-codec (v.4.1.77.Final) doesn't have ValueValidator in DefaultHeaders class, so the version needs to be upgraded to 4.1.86.Final.
error message from PR (https://github.com/Azure/azure-iot-sdk-java/pull/1645)
> Upgrade netty-codec version to 4.1.86.Final

- device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
Bug fix for issue #1629 
Currently we are never clearing the `correlationCallbacks` map in "IotHubTransport" class, even after the acknowledgement for received cloud to device message has been sent back to the hub. As a result, the size of map will grow endlessly which will result in OutOfMemory Error eventually.
> fix(iot-dev): Fix bug caused by unclearing correlationCallbacks map

- pom.xml
- Fix bug where correlationCallbacks map was not cleared properly and causing OutOfMemory #1647
- Fix bug where replace method did not work while initiating TwinClient with AzureSasCredential #1658
> release(2023-1-23): bump package versions

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/FileUploadTests.java
Marking getAndCompleteSasUriWithMultipleUploads flakeyTest as it is acting flakey on pipeline run
> Mark getAndCompleteSasUriWithMultipleUploads flakeyTest

- .gitignore
- iot-e2e-tests/common/pom.xml
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/proxy/impl/ClientToProxyConnection.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/helpers/rules/RerunFailedTestRule.java
- iot-e2e-tests/common/src/test/resources/log4j2.properties
- vsts/build_e2e_tests.cmd
- vsts/build_repo.ps1
- vsts/release/package-maven-artifacts-for-release.ps1
- vsts/sdl.yaml
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
- Fix issue where e2e tests were run __twice__ (once by failsafe plugin in parallel, once by surefire plugin in serial)
- This issue does not repro locally, so I'm not sure why this is happening, but this fix works locally and for the gate 
- Fix issue where rerun test rule didn't account for tests throwing AssumptionViolatedException
- Fix issue where mvn commands were very noisy
- Fix issue where a test proxy log statement that happens a lot was the wrong verbosity
- Allow JDK 11 and 8 builds to run in parallel
- For PR builds, this is safe because we only run e2e tests on JDK 11. No need to worry about overloading the service
- For CI/Nightly builds, this may be too much for the service to handle, but I'll keep an eye on that and we can revert this if needed
These changes combined will …
> Fix some issues with the build gate

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/HubTierConnectionTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/SendMessagesCommon.java
This didn't cause any issues as far as I can tell, but we shouldn't be including private keys on device identities who don't use x509 authentication
> fix(e2e): Fix test bug where x509 authentication certs were given to SAS  authenticated devices

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/telemetry/SendMessagesTests.java
SendLargestMessage was never supposed to build a batch message of multiple max-sized messages. It was just supposed to be one max sized message
The mux tests here should not retry on open because they expect to throw an exception
> fix(e2e): fix some CI tests

- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
CI builds are running into throttling from the service when running both windows/linux jdk 8/11 e2e tests all at once.
> Run JDK versions in parallel for PR, serial for CI

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/ProvisioningTests.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
The cause of the registration failure (SSL handshake failure) was lost in the test code before because it wasn't set as the inner exception for the thrown exception. Now the SSL handshake failure exception is visible to the tests that need it.
> Fix how the provisioning invalid server cert tests handle the thrown exception

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/provisioning/setup/ProvisioningCommon.java
- iot-e2e-tests/iot-e2e-jvm-tests/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/ProvisioningTPMTests.java
- iothub/device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/TemperatureController.java
- iothub/device/iot-device-samples/pnp-device-sample/thermostat-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/Thermostat.java
- provisioning/provisioning-device-client-samples/provisioning-X509-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningX509Sample.java
- provisioning/provisioning-device-client-samples/provisioning-symmetrickey-group-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningSymmetricKeyEnrollmentGroupSample.java
- provisioning/provisioning-device-client-samples/provisioning-symmetrickey-individual-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningSymmetricKeyIndividualEnrollmentSample.java
- provisioning/provisioning-device-client-samples/provisioning-tpm-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningTpmSample.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/ProvisioningDeviceClient.java
A lot of our samples and tests are simplified with this and a lot of customers would probably benefit the same way.
> feat(dps-device): Add synchronous overloads for registerDevice

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientOptions.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/GatewayType.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionString.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenProvidedAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenSoftwareAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenWithRefreshAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubX509HardwareAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubX509SoftwareAuthenticationProvider.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/IotHubSasTokenHsmAuthenticationProvider.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/ClientConfigurationTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/IotHubConnectionStringTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/ModuleClientTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubAuthenticationProviderTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenAuthenticationProviderTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProviderTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenSoftwareIotHubAuthenticationProviderTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenWithRefreshAuthenticationProviderTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/auth/IotHubX509HardwareIotHubAuthenticationProviderTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/hsm/IotHubSasTokenHsmAuthenticationProviderTest.java
Per new discussion we have, to specify E4K, more of us prefer to the option of adding a new property `GatewayType` (which can be one of two enum values "Edge" and "E4K") so that it can work with the existing property `GatewayHostName` which already supported for Edge. 
Also reverting the changes of adding `MqttGatewayHostName` committed [before](https://github.com/Azure/azure-iot-sdk-java/commit/8d152f70fe2816af5cd881bae5dc0753e334e6ed) in this PR.
> Add parameter GatewayType to specify E4K

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/CorrelationCallbackContext.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- Make correlation callback cleanup job run less frequently
- Previously ran several times per second. Now runs once per hour
- Make correlation callback operation blocks atomic
- We don't want cases where one thread is calling callbacks.get("some id") while another just removed that entry.
#1718
> Fix some threading issues with correlation callback maps

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientOptions.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClientOptions.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubReceiveTask.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubReconnectTask.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubSendTask.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/ReactorRunner.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/IotHubReceiveTaskTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/IotHubSendTaskTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnectionTest.java
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/transport/amqp/AmqpsConnection.java
- By default, don't change the existing behavior where threads are given unique prefix/postfix so users can correlate threads to clients
- Allow users to opt out of these unique thread names
- Allow users to provide custom prefix and postfix to thread names
#1715
> feat(iot-dev): Make SDK thread names configurable

- pom.xml
- Make SDK thread names configurable (#1720)
- Fix some threading issues around correlation callback map states (#1719)
- Add synchronous overloads for registerDevice (#1700)
> Bump versions for 6/6/2023 release

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/hsm/HttpsHsmClient.java
We didn't have any way to log the contents of the requests sent to the Edgelet over Unix domain socket
Also wrap a closeable stream in a try block so that it closes automatically
> fix(iot-dev): Add more trace logs to module client createFromEnvironment flow

- pom.xml
- Fix bug where sync overload of register ignores additional data (#1732)
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-device-client/2.1.1/jar
> Bump versions for 7/25/2023 release

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientOptions.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java
SAS authorized MQTT connections have routine disconnects that some users don't want treated as errors or warnings in logs. This adds a flag they can set in client options to opt out of the current default.
Also defer creating a multiplexing retry policy until a multiplexing client is created to avoid unnecessary logs
Like #1739 but requiring opting in to logging these routine disconnects opt-in
> feat(iot-dev): Allow users to opt-out of treating routine disconnects as errors

- vsts/StartEmulator.sh
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
The old code frequently timed out waiting for the android emulator to start, but this new code makes it much more consistently successful at starting up the emulator
> Fix android emulator testing

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientOptions.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ModuleClient.java
If a user provides a client options instance, but without an SSLContext, we should still keep all the settings they provided while adding the SSLContext generated by the SDK
> fix(iot-dev): fix bug where client options was overridden

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
- Fix bug where a closing multiplexed device would report its state as ```Disconnected``` followed by ```Disconnected_retrying``` and then finally ```Disconnected```
- Fix bug where a multiplexed device that has its device session closed didn't cancel all of its outgoing messages
- Fix bug where terminal retry states (retry expired, non-retryable exception encountered, etc.) didn't end reconnection attempts
> fix(iot-dev): Fix 3 multiplexing scenario bugs

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java
A recent customer issue revealed that very high values for this field result in the SDK repeatedly sending new SAS tokens due to an integer overflow
> fix(iot-dev): Add an upper limit to SAS token expiry time values

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/MultiplexingClientTests.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/twin/TwinCollection.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/TwinCollection.java
- provisioning/provisioning-service-client/src/test/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/TwinCollectionTest.java
IoT hub allows this so we should as well
> fix(iot-dev, prov-serv): Allow twin key to be empty string

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
If a client is struggling to open the connection (no network scenarios, for example), then users should be able to close the client without waiting for the retry to expire on the "open with retry" operation
#1759
> fix(iot-dev): fix bug where client opening with retry isn't cancelled by close

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientConfiguration.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientOptions.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceIO.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClientOptions.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java
Previously, the client would only check for expired messages each time it tried to send a message. Now it will check for expired messages even if the client is idle.
> feat(iot-dev): Add configurable message expiration check job

- provisioning/security/security-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/SecurityProviderSymmetricKey.java
- provisioning/security/security-provider/src/test/java/com/microsoft/azure/sdk/iot/provisioning/security/SecurityProviderSymmetricKeyTest.java
- provisioning/security/x509-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderX509Cert.java
Normally we don't do this kind of validation on the SDK side since the service is the source of truth on what characters are allowed, but these particular characters break the service's request path logic so they are don't log like normal requests.
TPM security providers already do more extensive validation of the registration id, so this commit only adds it for x509 and symmetric key cases
> refactor(prov-dev): Add SDK-side check for "/" and "\" characters in registrationId

- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsReceiverLinkHandler.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSenderLinkHandler.java
gwv2 hubs send a "link detach" event when a device is disabled, so we need to respond to this event by notifying higher layers that the link was lost.
For reference, gwv1 hubs send a "link close" event which we already handle
> fix(iot-dev): Fix bug where link detach events were ignored

- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqtt.java
The exception message suggests that we are checking if the client is already open, not if it is already closed.
#1772
> fix(prov-dev): Fix small logic error around multiple open calls in MQTT layer

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/setup/TwinCommon.java
- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/twin/TwinTests.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportMessage.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttTwin.java
- iothub/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/twin/ReportedPropertiesUpdateResponse.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransportMessageTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttTwinTest.java
- iothub/device/iot-device-client/src/test/java/com/microsoft/azure/sdk/iot/device/twin/DeviceTwinMessageTest.java
#1777 but with an integration test added and a little code cleanup
> Allow device/module client to send reported properties without specifying the version

- iot-e2e-tests/common/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/iothub/FileUploadTests.java
- iot-e2e-tests/device-deletion-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceDeletionSample.java
- vsts/windowsLinuxAndAndroidBuildMatrixConfig.yaml
Also make linux jobs run on 1ES hosted agent so that they can access the ACR container the TPM simulator image
> Disable file upload tests while test infrastructure is replaced

- pom.xml
- provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/SDKUtils.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroup.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollment.java
- provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/contract/SDKUtils.java
- provisioning/provisioning-service-client/src/test/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroupTest.java
- provisioning/provisioning-service-client/src/test/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/IndividualEnrollmentTest.java
Preparing a new public preview API release for DPS Service APIs 
Adding a new field "CredentialPolicyName" in EnrollmentGruop and IndividualEnrollment. This change will be introduced as part of 2025-07-01-preview API.
> [DPS][Public Preview] Provisioniong Service SDK Update
